/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package gui;

import java.awt.Dimension;
import java.awt.GridLayout;
import javax.swing.JPanel;
import javax.swing.JTextField;
import javax.swing.border.EmptyBorder;

/**
 *
 * @author Minh Hieu
 */
public class Frame_ListPhong extends javax.swing.JFrame {

    /**
     * Creates new form Frame
     */
    public Frame_ListPhong() {
        initComponents();
        addPhongToList(dataTmp());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Panel_Container_Fram = new javax.swing.JPanel();
        lableFilterOption1 = new javax.swing.JLabel();
        lableFilterOption2 = new javax.swing.JLabel();
        lableFilterOption3 = new javax.swing.JLabel();
        ComboFilterOption1 = new javax.swing.JComboBox<>();
        ComboFilterOption2 = new javax.swing.JComboBox<>();
        ComboFilterOption3 = new javax.swing.JComboBox<>();
        panel_Container_ListPhong = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(1920, 964));
        setMinimumSize(new java.awt.Dimension(1920, 964));
        setPreferredSize(new java.awt.Dimension(1920, 964));

        Panel_Container_Fram.setBackground(new java.awt.Color(204, 204, 255));
        Panel_Container_Fram.setMaximumSize(new java.awt.Dimension(108, 108));

        lableFilterOption1.setText("Sắp xếp loại phòng");

        lableFilterOption2.setText("Sắp xếp trạng thái:");

        lableFilterOption3.setText("Sắp xếp sức chứa:");

        ComboFilterOption1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        ComboFilterOption1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ComboFilterOption1ActionPerformed(evt);
            }
        });

        ComboFilterOption2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        ComboFilterOption2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ComboFilterOption2MouseClicked(evt);
            }
        });

        ComboFilterOption3.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        panel_Container_ListPhong.setBackground(new java.awt.Color(204, 204, 204));
        panel_Container_ListPhong.setLayout(new java.awt.GridLayout());

        javax.swing.GroupLayout Panel_Container_FramLayout = new javax.swing.GroupLayout(Panel_Container_Fram);
        Panel_Container_Fram.setLayout(Panel_Container_FramLayout);
        Panel_Container_FramLayout.setHorizontalGroup(
            Panel_Container_FramLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Panel_Container_FramLayout.createSequentialGroup()
                .addGap(62, 62, 62)
                .addGroup(Panel_Container_FramLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(panel_Container_ListPhong, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(Panel_Container_FramLayout.createSequentialGroup()
                        .addGroup(Panel_Container_FramLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lableFilterOption1, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ComboFilterOption1, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 159, Short.MAX_VALUE)
                        .addGroup(Panel_Container_FramLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(ComboFilterOption2, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lableFilterOption3))
                        .addGap(157, 157, 157)
                        .addGroup(Panel_Container_FramLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(ComboFilterOption3, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lableFilterOption2))))
                .addGap(102, 102, 102))
        );
        Panel_Container_FramLayout.setVerticalGroup(
            Panel_Container_FramLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Panel_Container_FramLayout.createSequentialGroup()
                .addGroup(Panel_Container_FramLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(Panel_Container_FramLayout.createSequentialGroup()
                        .addGap(52, 52, 52)
                        .addComponent(lableFilterOption1))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Panel_Container_FramLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(Panel_Container_FramLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lableFilterOption3)
                            .addComponent(lableFilterOption2))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(Panel_Container_FramLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(Panel_Container_FramLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(ComboFilterOption1, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(ComboFilterOption2, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(ComboFilterOption3, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(panel_Container_ListPhong, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(836, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(Panel_Container_Fram, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 822, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Panel_Container_Fram, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ComboFilterOption1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ComboFilterOption1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ComboFilterOption1ActionPerformed

    private void ComboFilterOption2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ComboFilterOption2MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_ComboFilterOption2MouseClicked

    private void A_Phong_Mouse_Entered(java.awt.event.MouseEvent evt) {                                                
       
    }    
    
    private String[] dataTmp(){
        return new String[] {"Phong 1","Phong 2","Phong 3"};
    }
    
    private JPanel CreateGUI_A_Phong(String Status_Phong,String SucChua,String CodePhong){
        GUI_A_Phong = new javax.swing.JPanel();
        icon_Status = new javax.swing.JLabel();
        label_PhongCode = new javax.swing.JLabel();
        label_SucChua = new javax.swing.JLabel();
        txt_SucChua = new javax.swing.JLabel();
        label_Nguoi = new javax.swing.JLabel();
        txt_PhongCode = new javax.swing.JLabel();
        
        if(Status_Phong.equalsIgnoreCase("Empty")){
            icon_Status.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icon_Status_Available.png"))); // NOI18N
        }
        else if(Status_Phong.equalsIgnoreCase("Waiting")){
            icon_Status.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icon_Status_Wating.png"))); // NOI18N
        }
        else{
           icon_Status.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icon_Status_Unvailable123.png"))); // NOI18N 
        }
         
        
        label_PhongCode.setText("Phòng:");

        label_SucChua.setText("Sức chứa: ");

        txt_SucChua.setText(SucChua);

        label_Nguoi.setText("Người");

        txt_PhongCode.setText(CodePhong);

        javax.swing.GroupLayout GUI_A_PhongLayout = new javax.swing.GroupLayout(GUI_A_Phong);
        GUI_A_Phong.setLayout(GUI_A_PhongLayout);
        GUI_A_PhongLayout.setHorizontalGroup(
            GUI_A_PhongLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(GUI_A_PhongLayout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(icon_Status)
                .addGap(47, 47, 47)
                .addGroup(GUI_A_PhongLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(GUI_A_PhongLayout.createSequentialGroup()
                        .addComponent(label_SucChua, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(txt_SucChua)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(label_Nguoi, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(GUI_A_PhongLayout.createSequentialGroup()
                        .addComponent(label_PhongCode, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(txt_PhongCode)))
                .addContainerGap(36, Short.MAX_VALUE))
        );
        GUI_A_PhongLayout.setVerticalGroup(
            GUI_A_PhongLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(GUI_A_PhongLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(GUI_A_PhongLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(label_PhongCode)
                    .addComponent(txt_PhongCode))
                .addGroup(GUI_A_PhongLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(GUI_A_PhongLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(icon_Status))
                    .addGroup(GUI_A_PhongLayout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addGroup(GUI_A_PhongLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(label_SucChua)
                            .addComponent(txt_SucChua)
                            .addComponent(label_Nguoi))))
                .addContainerGap(42, Short.MAX_VALUE))
        );
        
        return GUI_A_Phong;
    }
    
    private void addPhongToList(String[] list){
         
         panel_Container_ListPhong.setLayout(new GridLayout(0,3,20,20));
         panel_Container_ListPhong.setBorder(new EmptyBorder(10,10,10,10));
         
         
         for (String list1 : list){
              
              panel_Container_ListPhong.add(CreateGUI_A_Phong("Empty","12","123"));
         }
         
         for (String list1 : list){
              panel_Container_ListPhong.add( CreateGUI_A_Phong("Waiting","12","123"));
         }
         
         for (String list1 : list){
              panel_Container_ListPhong.add( CreateGUI_A_Phong("full","12","123"));
         }
         
        
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Frame_ListPhong.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Frame_ListPhong.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Frame_ListPhong.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Frame_ListPhong.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Frame_ListPhong().setVisible(true);
            }
        });
    }

    private javax.swing.JPanel GUI_A_Phong;
    private javax.swing.JLabel icon_Status;
    private javax.swing.JLabel label_Nguoi;
    private javax.swing.JLabel label_PhongCode;
    private javax.swing.JLabel label_SucChua;
    
    private javax.swing.JLabel txt_PhongCode;
    private javax.swing.JLabel txt_SucChua;
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> ComboFilterOption1;
    private javax.swing.JComboBox<String> ComboFilterOption2;
    private javax.swing.JComboBox<String> ComboFilterOption3;
    private javax.swing.JPanel Panel_Container_Fram;
    private javax.swing.JLabel lableFilterOption1;
    private javax.swing.JLabel lableFilterOption2;
    private javax.swing.JLabel lableFilterOption3;
    private javax.swing.JPanel panel_Container_ListPhong;
    // End of variables declaration//GEN-END:variables

    private Dimension Dimension(int i, int i0) {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }
}
