/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package gui;

import com.formdev.flatlaf.themes.FlatMacLightLaf;
import java.io.File;
import java.io.FileNotFoundException;
import java.util.ArrayList;
import java.util.Formatter;
import java.util.Scanner;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.UIManager;

/**
 *
 * @author Admin
 */
public class GD_CaiDat extends javax.swing.JFrame {

    /**
     * Creates new form GD_CaiDat
     */
    public GD_CaiDat() throws FileNotFoundException {
        FlatMacLightLaf.setup();
        UIManager.put( "Button.arc", 10 );
        UIManager.put( "Component.arc", 10 );
        UIManager.put( "ProgressBar.arc", 10 );
        UIManager.put( "TextComponent.arc", 10 );
        initComponents();
        loadFileTextField();
    }
    
    public void loadFileTextField() throws FileNotFoundException{
        File file = new File("SettingVoucher.txt");

        ArrayList<int[]> diemTichLuy = new ArrayList<>();
        // file tồn tại -> đọc
        if (file.exists()){   
            Scanner sc = new Scanner(file);
            
            diemTichLuy.add(new int[]{Integer.valueOf(sc.nextLine())});
            while (sc.hasNextLine()){
                String[] temp = sc.nextLine().split(";");
                diemTichLuy.add(new int[]{Integer.valueOf(temp[0]), Integer.valueOf(temp[1])});
            }
        }
        // file không tồn tại-> tạo
        else{
            Formatter createFile = new Formatter(file);
            //DATA TEMP
            diemTichLuy = new ArrayList<>();
            diemTichLuy.add(new int[]{0});
            diemTichLuy.add(new int[]{0, 0});
            diemTichLuy.add(new int[]{0, 0});
            diemTichLuy.add(new int[]{0, 0});
            
            
            writeFile(diemTichLuy);
            createFile.close();
        }
        
        textField_SoThue.setText(diemTichLuy.get(0)[0] + "");
        textField_Diem1.setText(diemTichLuy.get(1)[0] + "");
        textField_Giam1.setText(diemTichLuy.get(1)[1] + "");
        textField_Diem2.setText(diemTichLuy.get(2)[0] + "");
        textField_Giam2.setText(diemTichLuy.get(2)[1] + "");
        textField_Diem3.setText(diemTichLuy.get(3)[0] + "");
        textField_Giam3.setText(diemTichLuy.get(3)[1] + "");


    }
    
    public void writeFile(ArrayList<int[]> data) throws FileNotFoundException{
        File file = new File("SettingVoucher.txt");
        Formatter f = new Formatter(file);
        for (int[] is : data) {
            if (is.length == 1 ){
                f.format("%d\n", is[0]);
            }
            else{
                f.format("%d;%d\n", is[0], is[1]);
            }
        }
        f.close();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        textField_SoThue = new javax.swing.JTextField();
        jPanel5 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        textField_Diem1 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jPanel8 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        textField_Giam1 = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jPanel9 = new javax.swing.JPanel();
        jPanel10 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        textField_Diem2 = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jPanel11 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        textField_Giam2 = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jPanel12 = new javax.swing.JPanel();
        jPanel13 = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        textField_Diem3 = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        jPanel14 = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();
        textField_Giam3 = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        jPanel15 = new javax.swing.JPanel();
        rSButtonHover1 = new rojerusan.RSButtonHover();
        rSButtonHover2 = new rojerusan.RSButtonHover();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(650, 370));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new java.awt.BorderLayout());

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Cài đặt thanh toán", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI Black", 1, 18))); // NOI18N

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel1.setText("Số thuế (%):");

        textField_SoThue.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        textField_SoThue.setText("0");
        textField_SoThue.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textField_SoThueActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 527, Short.MAX_VALUE)
            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel3Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(textField_SoThue, javax.swing.GroupLayout.PREFERRED_SIZE, 413, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 48, Short.MAX_VALUE)
            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel3Layout.createSequentialGroup()
                    .addGap(10, 10, 10)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(textField_SoThue, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel1))
                    .addContainerGap(10, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(62, 62, 62)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(49, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel2, java.awt.BorderLayout.NORTH);

        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Cài đặt điểm tích lũy", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI Black", 1, 18))); // NOI18N
        jPanel5.setLayout(new javax.swing.BoxLayout(jPanel5, javax.swing.BoxLayout.Y_AXIS));

        jPanel6.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 40, 5));

        jPanel7.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 20, 5));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel4.setText("Trên:");
        jPanel7.add(jLabel4);

        textField_Diem1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        textField_Diem1.setText("0");
        textField_Diem1.setPreferredSize(new java.awt.Dimension(100, 26));
        textField_Diem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textField_Diem1ActionPerformed(evt);
            }
        });
        jPanel7.add(textField_Diem1);

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel3.setText("(điểm)");
        jPanel7.add(jLabel3);

        jPanel6.add(jPanel7);

        jPanel8.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 20, 5));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel7.setText("Giảm:");
        jPanel8.add(jLabel7);

        textField_Giam1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        textField_Giam1.setText("0");
        textField_Giam1.setPreferredSize(new java.awt.Dimension(100, 26));
        textField_Giam1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textField_Giam1ActionPerformed(evt);
            }
        });
        jPanel8.add(textField_Giam1);

        jLabel8.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel8.setText("(%)");
        jPanel8.add(jLabel8);

        jPanel6.add(jPanel8);

        jPanel5.add(jPanel6);

        jPanel9.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 40, 5));

        jPanel10.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 20, 5));

        jLabel9.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel9.setText("Trên:");
        jPanel10.add(jLabel9);

        textField_Diem2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        textField_Diem2.setText("0");
        textField_Diem2.setPreferredSize(new java.awt.Dimension(100, 26));
        textField_Diem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textField_Diem2ActionPerformed(evt);
            }
        });
        jPanel10.add(textField_Diem2);

        jLabel10.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel10.setText("(điểm)");
        jPanel10.add(jLabel10);

        jPanel9.add(jPanel10);

        jPanel11.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 20, 5));

        jLabel11.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel11.setText("Giảm:");
        jPanel11.add(jLabel11);

        textField_Giam2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        textField_Giam2.setText("0");
        textField_Giam2.setPreferredSize(new java.awt.Dimension(100, 26));
        textField_Giam2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textField_Giam2ActionPerformed(evt);
            }
        });
        jPanel11.add(textField_Giam2);

        jLabel12.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel12.setText("(%)");
        jPanel11.add(jLabel12);

        jPanel9.add(jPanel11);

        jPanel5.add(jPanel9);

        jPanel12.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 40, 5));

        jPanel13.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 20, 5));

        jLabel13.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel13.setText("Trên:");
        jPanel13.add(jLabel13);

        textField_Diem3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        textField_Diem3.setText("0");
        textField_Diem3.setPreferredSize(new java.awt.Dimension(100, 26));
        textField_Diem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textField_Diem3ActionPerformed(evt);
            }
        });
        jPanel13.add(textField_Diem3);

        jLabel14.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel14.setText("(điểm)");
        jPanel13.add(jLabel14);

        jPanel12.add(jPanel13);

        jPanel14.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 20, 5));

        jLabel15.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel15.setText("Giảm:");
        jPanel14.add(jLabel15);

        textField_Giam3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        textField_Giam3.setText("0");
        textField_Giam3.setPreferredSize(new java.awt.Dimension(100, 26));
        textField_Giam3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textField_Giam3ActionPerformed(evt);
            }
        });
        jPanel14.add(textField_Giam3);

        jLabel16.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel16.setText("(%)");
        jPanel14.add(jLabel16);

        jPanel12.add(jPanel14);

        jPanel5.add(jPanel12);

        jPanel1.add(jPanel5, java.awt.BorderLayout.SOUTH);

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        rSButtonHover1.setBackground(new java.awt.Color(0, 204, 204));
        rSButtonHover1.setText("Hủy");
        rSButtonHover1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rSButtonHover1ActionPerformed(evt);
            }
        });
        jPanel15.add(rSButtonHover1);

        rSButtonHover2.setBackground(new java.awt.Color(0, 204, 204));
        rSButtonHover2.setText("Xác nhận");
        rSButtonHover2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                confirmPress(evt);
            }
        });
        rSButtonHover2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rSButtonHover2ActionPerformed(evt);
            }
        });
        jPanel15.add(rSButtonHover2);

        getContentPane().add(jPanel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 260, 650, 50));

        setSize(new java.awt.Dimension(666, 322));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void textField_SoThueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textField_SoThueActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textField_SoThueActionPerformed

    private void textField_Diem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textField_Diem1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textField_Diem1ActionPerformed

    private void textField_Giam1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textField_Giam1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textField_Giam1ActionPerformed

    private void textField_Diem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textField_Diem2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textField_Diem2ActionPerformed

    private void textField_Giam2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textField_Giam2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textField_Giam2ActionPerformed

    private void textField_Diem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textField_Diem3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textField_Diem3ActionPerformed

    private void textField_Giam3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textField_Giam3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textField_Giam3ActionPerformed

    private void rSButtonHover1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rSButtonHover1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rSButtonHover1ActionPerformed

    private void rSButtonHover2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rSButtonHover2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rSButtonHover2ActionPerformed

    private void confirmPress(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_confirmPress

    try{
            Integer.parseInt(textField_SoThue.getText());
            Integer.parseInt(textField_Diem1.getText());
            Integer.parseInt(textField_Diem2.getText());
            Integer.parseInt(textField_Diem3.getText());
            Integer.parseInt(textField_Giam1.getText());
            Integer.parseInt(textField_Giam2.getText());
            Integer.parseInt(textField_Giam3.getText());


        } 
    catch (NumberFormatException ex){
            JOptionPane.showMessageDialog(null, "Ký tự phải là số");
        }
    if (textField_SoThue.getText().trim() == "" || Integer.valueOf(textField_SoThue.getText()) <0)
        JOptionPane.showMessageDialog(null, "Số thuế không được âm và không được rỗng");
    if (textField_Diem1.getText().trim() == "" || Integer.valueOf(textField_Diem1.getText()) <0)
        JOptionPane.showMessageDialog(null, "Số điểm không được âm và không được rỗng");
    if (textField_Diem2.getText().trim() == "" || Integer.valueOf(textField_Diem2.getText()) <0)
        JOptionPane.showMessageDialog(null, "Số điểm không được âm và không được rỗng");
    if (textField_Diem3.getText().trim() == "" || Integer.valueOf(textField_Diem3.getText()) <0)
        JOptionPane.showMessageDialog(null, "Số điểm không được âm và không được rỗng");
    if (textField_Giam1.getText().trim() == "" || Integer.valueOf(textField_Giam1.getText()) <0 || Integer.valueOf(textField_Giam1.getText()) >100)
        JOptionPane.showMessageDialog(null, "Số tiền giảm không được âm, từ 0 đến 100 và không được rỗng");
    if (textField_Giam2.getText().trim() == "" || Integer.valueOf(textField_Giam2.getText()) <0 || Integer.valueOf(textField_Giam2.getText()) >100)
        JOptionPane.showMessageDialog(null, "Số tiền giảm không được âm, từ 0 đến 100 và không được rỗng");
    if (textField_Giam3.getText().trim() == "" || Integer.valueOf(textField_Giam3.getText()) <0 || Integer.valueOf(textField_Giam3.getText()) >100)
        JOptionPane.showMessageDialog(null, "Số tiền giảm không được âm, từ 0 đến 100 và không được rỗng");
    
        ArrayList<int[]> data = new ArrayList<>();
        data.add(new int[]{Integer.valueOf(textField_SoThue.getText())});
        data.add(new int[]{Integer.valueOf(textField_Diem1.getText()), Integer.valueOf(textField_Giam1.getText())});
        data.add(new int[]{Integer.valueOf(textField_Diem2.getText()), Integer.valueOf(textField_Giam2.getText())});
        data.add(new int[]{Integer.valueOf(textField_Diem3.getText()), Integer.valueOf(textField_Giam3.getText())});
        
    
        try {
            writeFile(data);
        } catch (FileNotFoundException ex) {
            Logger.getLogger(GD_CaiDat.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        JOptionPane.showMessageDialog(null, "Cập nhập thành công");
        this.dispose();
    }//GEN-LAST:event_confirmPress

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GD_CaiDat.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GD_CaiDat.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GD_CaiDat.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GD_CaiDat.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new GD_CaiDat().setVisible(true);
                } catch (FileNotFoundException ex) {
                    Logger.getLogger(GD_CaiDat.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel14;
    private javax.swing.JPanel jPanel15;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private rojerusan.RSButtonHover rSButtonHover1;
    private rojerusan.RSButtonHover rSButtonHover2;
    private javax.swing.JTextField textField_Diem1;
    private javax.swing.JTextField textField_Diem2;
    private javax.swing.JTextField textField_Diem3;
    private javax.swing.JTextField textField_Giam1;
    private javax.swing.JTextField textField_Giam2;
    private javax.swing.JTextField textField_Giam3;
    private javax.swing.JTextField textField_SoThue;
    // End of variables declaration//GEN-END:variables
}
