/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package gui;

/**
 *
 * @author Admin
 */
public class GD_QuanLi_Panel extends javax.swing.JPanel {
    GD_QuanLi_Phong p = new GD_QuanLi_Phong();
    GD_QuanLi_LoaiPhong lp = new GD_QuanLi_LoaiPhong();
    GD_QuanLi_KhachHang kh = new GD_QuanLi_KhachHang();
    GD_QuanLi_DichVu dv = new GD_QuanLi_DichVu();
    GD_QuanLi_NhanVien nv = new GD_QuanLi_NhanVien();
    GD_QuanLi_ChucVu cv = new GD_QuanLi_ChucVu();
    GD_QuanLi_Ca ca = new GD_QuanLi_Ca();
    GD_QuanLi_UuDai ud = new GD_QuanLi_UuDai();
    /**
     * Creates new form GD_QuanLi_Panel
     */
    public GD_QuanLi_Panel() {
        initComponents();
        jTabbedPane1.addTab("Quản lí Phòng", p.getContentPane());
        jTabbedPane1.addTab("Quản lí Loại phòng", lp.getContentPane());
        jTabbedPane1.addTab("Quản lí Dịch vụ", dv.getContentPane());
        jTabbedPane1.addTab("Quản lí Ưu đãi", ud.getContentPane());
        jTabbedPane1.addTab("Quản lí Khách hàng", kh.getContentPane());
        jTabbedPane1.addTab("Quản lí Nhân viên", nv.getContentPane());
        jTabbedPane1.addTab("Quản lí Chức vụ", cv.getContentPane());
        jTabbedPane1.addTab("Quản lí Ca", ca.getContentPane());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();

        setMaximumSize(new java.awt.Dimension(1920, 964));
        setMinimumSize(new java.awt.Dimension(1920, 964));
        setPreferredSize(new java.awt.Dimension(1920, 964));

        jTabbedPane1.setFont(new java.awt.Font("Segoe UI", 0, 28)); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 1920, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 964, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTabbedPane jTabbedPane1;
    // End of variables declaration//GEN-END:variables
}
