/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package gui;

import com.microsoft.sqlserver.jdbc.SQLServerException;
import dao.DAO_KhachHang;
import entity.KhachHang;
import java.awt.Font;
import java.awt.HeadlessException;
import java.util.ArrayList;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.JTableHeader;
import javax.swing.table.TableCellRenderer;

/**
 *
 * @author quang
 */
public class GD_QuanLi_KhachHang extends javax.swing.JFrame implements I_TraCuu_QuanLi<KhachHang>{

    /**
     * Creates new form GD_QuanLiKhachHang
     */
    public GD_QuanLi_KhachHang() {
        initComponents();
        model = (DefaultTableModel) tbl_danhSach.getModel();
        setEnableInput(false, jPanel11);
        loadTable(dskh, model);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel9 = new javax.swing.JPanel();
        jPanel10 = new javax.swing.JPanel();
        jPanel11 = new javax.swing.JPanel();
        jPanel12 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        tf_phone = new javax.swing.JTextField();
        jPanel13 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        tf_ten = new javax.swing.JTextField();
        jPanel24 = new javax.swing.JPanel();
        jPanel25 = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();
        jPanel26 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tbl_danhSach = new javax.swing.JTable();
        jPanel27 = new javax.swing.JPanel();
        btn_them = new javax.swing.JButton();
        btn_sua = new javax.swing.JButton();
        btn_luu = new javax.swing.JButton();
        btn_xoaTrang = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel9.setBackground(new java.awt.Color(142, 172, 207));
        jPanel9.setBorder(javax.swing.BorderFactory.createEmptyBorder(20, 20, 20, 20));
        jPanel9.setPreferredSize(new java.awt.Dimension(1920, 763));

        jPanel10.setBorder(javax.swing.BorderFactory.createEmptyBorder(10, 10, 10, 10));

        jPanel11.setPreferredSize(new java.awt.Dimension(290, 1141));
        jPanel11.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 0, 7));

        jPanel12.setPreferredSize(new java.awt.Dimension(283, 83));
        jPanel12.setLayout(new java.awt.BorderLayout(0, 5));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel3.setText("Số điện thoại:");
        jPanel12.add(jLabel3, java.awt.BorderLayout.NORTH);

        tf_phone.setBackground(new java.awt.Color(142, 172, 207));
        tf_phone.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jPanel12.add(tf_phone, java.awt.BorderLayout.CENTER);

        jPanel11.add(jPanel12);

        jPanel13.setPreferredSize(new java.awt.Dimension(283, 83));
        jPanel13.setLayout(new java.awt.BorderLayout(0, 5));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel4.setText("Tên khách hàng:");
        jPanel13.add(jLabel4, java.awt.BorderLayout.NORTH);

        tf_ten.setBackground(new java.awt.Color(142, 172, 207));
        tf_ten.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jPanel13.add(tf_ten, java.awt.BorderLayout.CENTER);

        jPanel11.add(jPanel13);

        jPanel10.add(jPanel11);

        jPanel24.setLayout(new java.awt.BorderLayout());

        jLabel15.setFont(new java.awt.Font("Segoe UI Black", 1, 36)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(40, 77, 133));
        jLabel15.setText("DANH SÁCH KHÁCH HÀNG");
        jPanel25.add(jLabel15);

        jPanel24.add(jPanel25, java.awt.BorderLayout.NORTH);

        jPanel26.setBorder(javax.swing.BorderFactory.createEmptyBorder(20, 20, 10, 20));
        jPanel26.setPreferredSize(new java.awt.Dimension(1511, 1200));
        jPanel26.setLayout(new java.awt.BorderLayout());

        jScrollPane2.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_ALWAYS);

        tbl_danhSach.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Số điện thoại", "Tên khách hàng"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tbl_danhSach.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        tbl_danhSach.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        tbl_danhSach.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbl_danhSachMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tbl_danhSach);
        tbl_danhSach.setRowHeight(35);
        // Chỉnh font cho header
        JTableHeader header = tbl_danhSach.getTableHeader();
        header.setFont(new Font("Segoe UI", Font.PLAIN, 20));
        // Căn lề cho header
        TableCellRenderer rendererFromHeader = header.getDefaultRenderer();
        JLabel headerLabel = (JLabel) rendererFromHeader;
        headerLabel.setHorizontalAlignment(JLabel.CENTER);

        jPanel26.add(jScrollPane2, java.awt.BorderLayout.CENTER);

        jPanel24.add(jPanel26, java.awt.BorderLayout.CENTER);

        jPanel27.setBorder(javax.swing.BorderFactory.createEmptyBorder(10, 10, 10, 10));
        jPanel27.setPreferredSize(new java.awt.Dimension(1520, 80));
        jPanel27.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 15, 5));

        btn_them.setBackground(new java.awt.Color(40, 77, 133));
        btn_them.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        btn_them.setForeground(new java.awt.Color(255, 255, 255));
        btn_them.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/quanLi_add30.png"))); // NOI18N
        btn_them.setText("Thêm");
        btn_them.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GD_QuanLi_KhachHang.this.actionPerformed(evt);
            }
        });
        jPanel27.add(btn_them);

        btn_sua.setBackground(new java.awt.Color(40, 77, 133));
        btn_sua.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        btn_sua.setForeground(new java.awt.Color(255, 255, 255));
        btn_sua.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/quanLi_edit30.png"))); // NOI18N
        btn_sua.setText("Sửa");
        btn_sua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GD_QuanLi_KhachHang.this.actionPerformed(evt);
            }
        });
        jPanel27.add(btn_sua);

        btn_luu.setBackground(new java.awt.Color(40, 77, 133));
        btn_luu.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        btn_luu.setForeground(new java.awt.Color(255, 255, 255));
        btn_luu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/quanLi_save30.png"))); // NOI18N
        btn_luu.setText("Lưu");
        btn_luu.setEnabled(false);
        btn_luu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GD_QuanLi_KhachHang.this.actionPerformed(evt);
            }
        });
        jPanel27.add(btn_luu);

        btn_xoaTrang.setBackground(new java.awt.Color(40, 77, 133));
        btn_xoaTrang.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        btn_xoaTrang.setForeground(new java.awt.Color(255, 255, 255));
        btn_xoaTrang.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/quanLi_clear30.png"))); // NOI18N
        btn_xoaTrang.setText("Xoá trắng");
        btn_xoaTrang.setEnabled(false);
        btn_xoaTrang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GD_QuanLi_KhachHang.this.actionPerformed(evt);
            }
        });
        jPanel27.add(btn_xoaTrang);

        jPanel24.add(jPanel27, java.awt.BorderLayout.SOUTH);

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addComponent(jPanel10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addComponent(jPanel24, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel10, javax.swing.GroupLayout.DEFAULT_SIZE, 924, Short.MAX_VALUE)
            .addComponent(jPanel24, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel9, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel9, javax.swing.GroupLayout.DEFAULT_SIZE, 964, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tbl_danhSachMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbl_danhSachMouseClicked
        // TODO add your handling code here:
        int i = tbl_danhSach.getSelectedRow();
        if (i != -1) {
            showDetailInput(jPanel11, model, i);
        }
    }//GEN-LAST:event_tbl_danhSachMouseClicked

    private void actionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_actionPerformed
        // TODO add your handling code here:
        Object o = evt.getSource();
        if (o.equals(btn_them)) {
            clearInput(jPanel11);
            if (btn_them.getText().equals("Thêm")) {
                tbl_danhSach.clearSelection();
                tbl_danhSach.setEnabled(false);
                setEnableInput(true, jPanel11);
                tf_phone.setEditable(true);
                btn_them.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/chuyenPhong_huy30.png")));
                btn_them.setText("Huỷ");
                btn_sua.setEnabled(false);
                btn_luu.setEnabled(true);
                btn_xoaTrang.setEnabled(true);
            } else {
                clearInput(jPanel11);
                tbl_danhSach.setEnabled(true);
                tf_phone.setText("");
                setEnableInput(false, jPanel11);
                btn_them.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/quanLi_add30.png")));
                btn_them.setText("Thêm");
                btn_sua.setEnabled(true);
                btn_luu.setEnabled(false);
                btn_xoaTrang.setEnabled(false);
            }
        } else if (o.equals(btn_sua)) {
            int r = tbl_danhSach.getSelectedRow();
            if (r != -1) {
                if (btn_sua.getText().equals("Sửa")) {
                    setEnableInput(true, jPanel11);
                    tf_phone.setEditable(true);
                    btn_sua.setText("Huỷ");
                    btn_sua.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/chuyenPhong_huy30.png")));
                    btn_them.setEnabled(false);
                    btn_luu.setEnabled(true);
                    btn_xoaTrang.setEnabled(true);
                    tbl_danhSach.setEnabled(false);
                } else {
                    tbl_danhSach.clearSelection();
                    tbl_danhSach.setEnabled(true);
                    clearInput(jPanel11);
                    tf_phone.setText("");
                    setEnableInput(false, jPanel11);
                    btn_sua.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/quanLi_edit30.png")));
                    btn_sua.setText("Sửa");
                    btn_them.setEnabled(true);
                    btn_luu.setEnabled(false);
                    btn_xoaTrang.setEnabled(false);
                }
            } else {
                JOptionPane.showMessageDialog(null, "Hãy chọn dòng");
            }
        } else if (o.equals(btn_luu)) {
            if (btn_them.getText().equals("Huỷ")) {
                if (validateInput()) { // để nhét regex vào
                    String phone = tf_phone.getText().trim();
                    String ten = tf_ten.getText().trim();
                    
                    KhachHang kh = new KhachHang(phone, ten);
                    if (daokh.create(kh)) {
                        JOptionPane.showMessageDialog(this, "Thêm thành công");
                        loadTable(daokh.getAll(KhachHang.class), model);
                        clearInput(jPanel11);
                        tbl_danhSach.setEnabled(true);
                        tf_phone.setText("");
                        setEnableInput(false, jPanel11);
                        btn_them.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/quanLi_add30.png")));
                        btn_them.setText("Thêm");
                        btn_sua.setEnabled(true);
                        btn_luu.setEnabled(false);
                        btn_xoaTrang.setEnabled(false);
                    } else {
                        JOptionPane.showMessageDialog(null, "Số điện thoại không được trùng", "Lỗi", JOptionPane.ERROR_MESSAGE);
                    }
                }
            }
            if (btn_sua.getText().equals("Huỷ")) {
                if (validateInput()) {
                    String phone = tf_phone.getText().trim();
                    String ten = tf_ten.getText().trim();
                    int row = tbl_danhSach.getSelectedRow();
                    KhachHang kh = new KhachHang(phone, ten);
                    
                    if (daokh.update(kh, model.getValueAt(row, 0).toString())) {
                        JOptionPane.showMessageDialog(this, "Sửa thành công");
                        loadTable(daokh.getAll(KhachHang.class), model);
                        tbl_danhSach.clearSelection();
                        tbl_danhSach.setEnabled(true);
                        clearInput(jPanel11);
                        tf_phone.setText("");
                        setEnableInput(false, jPanel11);
                        btn_sua.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/quanLi_edit30.png")));
                        btn_sua.setText("Sửa");
                        btn_them.setEnabled(true);
                        btn_luu.setEnabled(false);
                        btn_xoaTrang.setEnabled(false);
                    } else {
                        JOptionPane.showMessageDialog(null, "Số điện thoại không được trùng", "Lỗi", JOptionPane.ERROR_MESSAGE);
                    }
                }
            }
        } else if (o.equals(btn_xoaTrang)) {
            clearInput(jPanel11);
        }
    }//GEN-LAST:event_actionPerformed
    private boolean validateInput() {
        String ten = tf_ten.getText().trim();;
        String phone = tf_phone.getText().trim();
        if (phone.isEmpty()) {
            showRegexError(tf_phone, "Vui lòng nhập số điện thoại");
            return false;
        }
        if (!phone.matches("^0[1-9]\\d{8}$")) {
            showRegexError(tf_phone, "Số điện thoại bắt đầu bằng chữ số 0 và có tối đa 10 chữ số");
            return false;
        }
        if (ten.isEmpty()) {
            showRegexError(tf_ten, "Tên không được rỗng");
            return false;
        }
        if (ten.length() > 30) {
            showRegexError(tf_ten, "Tên không được quá 30 kí tự");
            return false;
        }
        if (!ten.matches("^[A-ZÀ-Ỹ][a-zà-ỹ]+(\\s[A-ZÀ-Ỹ][a-zà-ỹ]+)+$")) {
            showRegexError(tf_ten, "Mỗi kí tự đầu của từ phải viết Hoa, không bao gồm chữ số và kí tự đặc biệt");
            return false;
        }
        return true;
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GD_QuanLi_KhachHang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GD_QuanLi_KhachHang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GD_QuanLi_KhachHang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GD_QuanLi_KhachHang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GD_QuanLi_KhachHang().setVisible(true);
            }
        });
    }
    private DAO_KhachHang daokh = new DAO_KhachHang();
    private ArrayList<KhachHang> dskh = daokh.getAll(KhachHang.class);
    private DefaultTableModel model;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_luu;
    private javax.swing.JButton btn_sua;
    private javax.swing.JButton btn_them;
    private javax.swing.JButton btn_xoaTrang;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel24;
    private javax.swing.JPanel jPanel25;
    private javax.swing.JPanel jPanel26;
    private javax.swing.JPanel jPanel27;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable tbl_danhSach;
    private javax.swing.JTextField tf_phone;
    private javax.swing.JTextField tf_ten;
    // End of variables declaration//GEN-END:variables
}
