/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package gui;

import dao.DAO_Ca;
import dao.DAO_NhanVien;
import dao.DAO_TaiKhoan;
import dao.I_CRUD;
import entity.Ca;
import entity.NhanVien;
import entity.TaiKhoan;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.time.LocalDate;
import java.util.ArrayList;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author quang
 */
public class GD_ThongTinCaNhan extends javax.swing.JFrame  implements I_TraCuu_QuanLi<NhanVien>{

    /**
     * Creates new form GD_ThongTinCaNhan
     */
    public GD_ThongTinCaNhan() {
        initComponents();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jPanel19 = new javax.swing.JPanel();
        btn_edit_nhanvien = new javax.swing.JButton();
        btn_luu_nhanvien = new javax.swing.JButton();
        jPanel20 = new javax.swing.JPanel();
        btn_edit_mk = new javax.swing.JButton();
        btn_luu_mk = new javax.swing.JButton();
        jPanel21 = new javax.swing.JPanel();
        jPanel17 = new javax.swing.JPanel();
        jPanel16 = new javax.swing.JPanel();
        pw_new2 = new javax.swing.JPasswordField();
        jLabel13 = new javax.swing.JLabel();
        rd_show = new javax.swing.JRadioButton();
        jPanel14 = new javax.swing.JPanel();
        pw_old = new javax.swing.JPasswordField();
        jLabel11 = new javax.swing.JLabel();
        jPanel15 = new javax.swing.JPanel();
        pw_new = new javax.swing.JPasswordField();
        jLabel12 = new javax.swing.JLabel();
        jPanel22 = new javax.swing.JPanel();
        jPanel18 = new javax.swing.JPanel();
        jPanel8 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        tf_name = new javax.swing.JTextField();
        jPanel5 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        datechooser_ngaySinh = new com.toedter.calendar.JDateChooser();
        jPanel6 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        cb_gioiTinh = new javax.swing.JComboBox<>();
        jPanel7 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        tf_cmnd = new javax.swing.JTextField();
        jPanel9 = new javax.swing.JPanel();
        jPanel10 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        tf_diaChi = new javax.swing.JTextField();
        jPanel11 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        tf_phone = new javax.swing.JTextField();
        jPanel12 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        tf_gmail = new javax.swing.JTextField();
        jPanel13 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        cb_ca = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.addHierarchyListener(new java.awt.event.HierarchyListener() {
            public void hierarchyChanged(java.awt.event.HierarchyEvent evt) {
                jPanel1HierarchyChanged(evt);
            }
        });

        jPanel2.setBorder(javax.swing.BorderFactory.createEmptyBorder(10, 1, 1, 1));

        jLabel1.setFont(new java.awt.Font("Segoe UI Black", 1, 32)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 153, 153));
        jLabel1.setText("THÔNG TIN CÁ NHÂN");
        jPanel2.add(jLabel1);

        jPanel19.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 30, 5));

        btn_edit_nhanvien.setBackground(new java.awt.Color(0, 204, 204));
        btn_edit_nhanvien.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        btn_edit_nhanvien.setForeground(new java.awt.Color(255, 255, 255));
        btn_edit_nhanvien.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/quanLi_edit30.png"))); // NOI18N
        btn_edit_nhanvien.setText("Cập nhật");
        btn_edit_nhanvien.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                capNhatNhanVien(evt);
            }
        });
        jPanel19.add(btn_edit_nhanvien);

        btn_luu_nhanvien.setBackground(new java.awt.Color(0, 153, 153));
        btn_luu_nhanvien.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        btn_luu_nhanvien.setForeground(new java.awt.Color(255, 255, 255));
        btn_luu_nhanvien.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/quanLi_save30.png"))); // NOI18N
        btn_luu_nhanvien.setText("Lưu");
        btn_luu_nhanvien.setEnabled(false);
        btn_luu_nhanvien.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                capNhatNhanVien(evt);
            }
        });
        jPanel19.add(btn_luu_nhanvien);

        jPanel20.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 30, 5));

        btn_edit_mk.setBackground(new java.awt.Color(0, 204, 204));
        btn_edit_mk.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        btn_edit_mk.setForeground(new java.awt.Color(255, 255, 255));
        btn_edit_mk.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/quanLi_edit30.png"))); // NOI18N
        btn_edit_mk.setText("Cập nhật");
        btn_edit_mk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                capNhatMK(evt);
            }
        });
        jPanel20.add(btn_edit_mk);

        btn_luu_mk.setBackground(new java.awt.Color(0, 153, 153));
        btn_luu_mk.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        btn_luu_mk.setForeground(new java.awt.Color(255, 255, 255));
        btn_luu_mk.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/quanLi_save30.png"))); // NOI18N
        btn_luu_mk.setText("Lưu");
        btn_luu_mk.setEnabled(false);
        btn_luu_mk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                capNhatMK(evt);
            }
        });
        jPanel20.add(btn_luu_mk);

        jPanel17.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Đổi mật khẩu", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 24))); // NOI18N

        pw_new2.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N

        jLabel13.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel13.setText("Xác nhận lại mật khẩu:");

        javax.swing.GroupLayout jPanel16Layout = new javax.swing.GroupLayout(jPanel16);
        jPanel16.setLayout(jPanel16Layout);
        jPanel16Layout.setHorizontalGroup(
            jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel16Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 296, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(pw_new2, javax.swing.GroupLayout.PREFERRED_SIZE, 667, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel16Layout.setVerticalGroup(
            jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel16Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(pw_new2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        rd_show.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        rd_show.setText("Hiển thị mật khẩu");
        rd_show.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rd_showActionPerformed(evt);
            }
        });

        pw_old.setEditable(false);
        pw_old.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N

        jLabel11.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel11.setText("Mật khẩu cũ:");

        javax.swing.GroupLayout jPanel14Layout = new javax.swing.GroupLayout(jPanel14);
        jPanel14.setLayout(jPanel14Layout);
        jPanel14Layout.setHorizontalGroup(
            jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel14Layout.createSequentialGroup()
                .addContainerGap(19, Short.MAX_VALUE)
                .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(pw_old, javax.swing.GroupLayout.PREFERRED_SIZE, 667, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel14Layout.setVerticalGroup(
            jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel14Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(pw_old, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        pw_new.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N

        jLabel12.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel12.setText("Mật khẩu mới:");

        javax.swing.GroupLayout jPanel15Layout = new javax.swing.GroupLayout(jPanel15);
        jPanel15.setLayout(jPanel15Layout);
        jPanel15Layout.setHorizontalGroup(
            jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel15Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel12, javax.swing.GroupLayout.DEFAULT_SIZE, 211, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(pw_new, javax.swing.GroupLayout.PREFERRED_SIZE, 667, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel15Layout.setVerticalGroup(
            jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel15Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(pw_new, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel17Layout = new javax.swing.GroupLayout(jPanel17);
        jPanel17.setLayout(jPanel17Layout);
        jPanel17Layout.setHorizontalGroup(
            jPanel17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel17Layout.createSequentialGroup()
                .addGap(100, 100, 100)
                .addGroup(jPanel17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel14, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel15, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel17Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(rd_show)
                .addGap(14, 14, 14))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel17Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel16, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel17Layout.setVerticalGroup(
            jPanel17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel17Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel14, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel15, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel16, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(rd_show)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel21.add(jPanel17);

        jPanel18.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Thông tin nhân viên", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 24))); // NOI18N

        jPanel8.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 5, 10));

        jPanel4.setPreferredSize(new java.awt.Dimension(752, 70));
        jPanel4.setLayout(new java.awt.BorderLayout());

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel2.setText("Tên nhân viên:");
        jPanel4.add(jLabel2, java.awt.BorderLayout.PAGE_START);

        tf_name.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jPanel4.add(tf_name, java.awt.BorderLayout.CENTER);

        jPanel8.add(jPanel4);

        jPanel5.setPreferredSize(new java.awt.Dimension(752, 70));
        jPanel5.setLayout(new java.awt.BorderLayout());

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel3.setText("Ngày sinh:");
        jPanel5.add(jLabel3, java.awt.BorderLayout.PAGE_START);

        datechooser_ngaySinh.setDateFormatString("yyyy-MM-dd");
        datechooser_ngaySinh.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jPanel5.add(datechooser_ngaySinh, java.awt.BorderLayout.CENTER);

        jPanel8.add(jPanel5);

        jPanel6.setPreferredSize(new java.awt.Dimension(752, 70));
        jPanel6.setLayout(new java.awt.BorderLayout());

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel4.setText("Giới tính:");
        jPanel6.add(jLabel4, java.awt.BorderLayout.PAGE_START);

        cb_gioiTinh.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        cb_gioiTinh.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Nam", "Nữ" }));
        jPanel6.add(cb_gioiTinh, java.awt.BorderLayout.CENTER);

        jPanel8.add(jPanel6);

        jPanel7.setPreferredSize(new java.awt.Dimension(752, 70));
        jPanel7.setLayout(new java.awt.BorderLayout());

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel5.setText("CMND:");
        jPanel7.add(jLabel5, java.awt.BorderLayout.PAGE_START);

        tf_cmnd.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jPanel7.add(tf_cmnd, java.awt.BorderLayout.CENTER);

        jPanel8.add(jPanel7);

        jPanel9.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 5, 10));

        jPanel10.setPreferredSize(new java.awt.Dimension(752, 70));
        jPanel10.setLayout(new java.awt.BorderLayout());

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel6.setText("Địa chỉ:");
        jPanel10.add(jLabel6, java.awt.BorderLayout.PAGE_START);

        tf_diaChi.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jPanel10.add(tf_diaChi, java.awt.BorderLayout.CENTER);

        jPanel9.add(jPanel10);

        jPanel11.setPreferredSize(new java.awt.Dimension(752, 70));
        jPanel11.setLayout(new java.awt.BorderLayout());

        jLabel7.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel7.setText("Số điện thoại:");
        jPanel11.add(jLabel7, java.awt.BorderLayout.PAGE_START);

        tf_phone.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jPanel11.add(tf_phone, java.awt.BorderLayout.CENTER);

        jPanel9.add(jPanel11);

        jPanel12.setPreferredSize(new java.awt.Dimension(752, 70));
        jPanel12.setLayout(new java.awt.BorderLayout());

        jLabel8.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel8.setText("Gmail:");
        jPanel12.add(jLabel8, java.awt.BorderLayout.PAGE_START);

        tf_gmail.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jPanel12.add(tf_gmail, java.awt.BorderLayout.CENTER);

        jPanel9.add(jPanel12);

        jPanel13.setPreferredSize(new java.awt.Dimension(752, 70));
        jPanel13.setLayout(new java.awt.BorderLayout());

        jLabel9.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel9.setText("Ca:");
        jPanel13.add(jLabel9, java.awt.BorderLayout.PAGE_START);

        cb_ca.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jPanel13.add(cb_ca, java.awt.BorderLayout.CENTER);
        ArrayList<Ca> dsca = daoca.getAll(Ca.class);
        dsca.forEach(e -> {
            cb_ca.addItem(e.getTenCa());
        });

        jPanel9.add(jPanel13);

        javax.swing.GroupLayout jPanel18Layout = new javax.swing.GroupLayout(jPanel18);
        jPanel18.setLayout(jPanel18Layout);
        jPanel18Layout.setHorizontalGroup(
            jPanel18Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel18Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, 757, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(147, 147, 147)
                .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, 757, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel18Layout.setVerticalGroup(
            jPanel18Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel18Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel18Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel9, javax.swing.GroupLayout.DEFAULT_SIZE, 336, Short.MAX_VALUE)
                    .addComponent(jPanel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(0, 0, 0))
        );

        jPanel22.add(jPanel18);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel22, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel19, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel21, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jPanel20, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(jPanel22, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(15, 15, 15)
                .addComponent(jPanel19, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel21, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(15, 15, 15)
                .addComponent(jPanel20, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(94, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 1920, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void capNhatNhanVien(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_capNhatNhanVien
        // TODO add your handling code here:
        Object o = evt.getSource();
        if (o.equals(btn_edit_nhanvien)) {
            if (btn_edit_nhanvien.getText().equals("Cập nhật")) {
                btn_edit_nhanvien.setText("Huỷ");
                btn_edit_nhanvien.setIcon(new ImageIcon(getClass().getResource("/img/chuyenPhong_huy30.png")));
                btn_luu_nhanvien.setEnabled(true);
                moNhapLieuNhanVien(true);
            } else {
                btn_edit_nhanvien.setText("Cập nhật");
                btn_edit_nhanvien.setIcon(new ImageIcon(getClass().getResource("/img/quanLi_edit30.png")));
                btn_luu_nhanvien.setEnabled(false);
                loadNV();
                moNhapLieuNhanVien(false);
            }
        } else {
             if (validateInputNhanVien()) {
                String id = GD_DangNhap.taiKhoan.getNhanVien().getMaNhanVien();
                String ten = tf_name.getText().trim();
                SimpleDateFormat date = new SimpleDateFormat("yyy-MM-dd");
                String d = date.format(datechooser_ngaySinh.getDate());
                LocalDate ngaySinh = LocalDate.parse( d);
                boolean gioiTinh = cb_gioiTinh.getSelectedItem().toString().equals("Nam");
                String cmnd = tf_cmnd.getText().trim();
                String diaChi = tf_diaChi.getText().trim();
                String sdt = tf_phone.getText().trim();
                boolean trangThai = GD_DangNhap.taiKhoan.getNhanVien().getTrangThai();
                String gmail = tf_gmail.getText().trim();
                Ca ca = daoca.getCaTheoTen(cb_ca.getSelectedItem().toString());
                 
                NhanVien nv = new NhanVien(id, ten, ngaySinh, gioiTinh, cmnd, diaChi, sdt, trangThai, gmail, ca);
                TaiKhoan tk = new TaiKhoan(sdt, String.valueOf(pw_old.getPassword()), GD_DangNhap.taiKhoan.getVaiTro(), nv);
//                System.out.println(tk);
                if (daonv.update(nv) && daotk.updateTK(tk)) {
                    JOptionPane.showMessageDialog(this, "Cập nhật thành công");
                    btn_edit_nhanvien.setText("Cập nhật");
                    btn_edit_nhanvien.setIcon(new ImageIcon(getClass().getResource("/img/quanLi_edit30.png")));
                    btn_luu_nhanvien.setEnabled(false);
                    loadNV();
                    moNhapLieuNhanVien(false);
                }
            }
        }
        
    }//GEN-LAST:event_capNhatNhanVien

    private void capNhatMK(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_capNhatMK
        // TODO add your handling code here:
        Object o = evt.getSource();
        if (o.equals(btn_edit_mk)) {
            if (btn_edit_mk.getText().equals("Cập nhật")) {
                btn_edit_mk.setText("Huỷ");
                btn_edit_mk.setIcon(new ImageIcon(getClass().getResource("/img/chuyenPhong_huy30.png")));
                btn_luu_mk.setEnabled(true);
                moNhapLieuMatKhau(true);
            } else {
                btn_edit_mk.setText("Cập nhật");
                btn_edit_mk.setIcon(new ImageIcon(getClass().getResource("/img/quanLi_edit30.png")));
                btn_luu_mk.setEnabled(false);
                loadMK();
                moNhapLieuMatKhau(false);
            }
        } else {
            if (validateInputMK()) {
                NhanVien a = GD_DangNhap.taiKhoan.getNhanVien();
                TaiKhoan tk = new TaiKhoan(a.getSoDienThoai(), String.valueOf(pw_new2.getPassword()), GD_DangNhap.taiKhoan.getVaiTro(), a);
                if (daotk.update(tk)) { // dựa vào tenTK để update
                    JOptionPane.showMessageDialog(this, "Cập nhật thành công");
                    btn_edit_mk.setText("Cập nhật");
                    btn_edit_mk.setIcon(new ImageIcon(getClass().getResource("/img/quanLi_edit30.png")));
                    btn_luu_mk.setEnabled(false);
                    loadMK();
                    moNhapLieuMatKhau(false);
                }
            }
        }
    }//GEN-LAST:event_capNhatMK

    private void jPanel1HierarchyChanged(java.awt.event.HierarchyEvent evt) {//GEN-FIRST:event_jPanel1HierarchyChanged
        // TODO add your handling code here:
        if (jPanel1.isShowing()) {
            moNhapLieuNhanVien(false);
            moNhapLieuMatKhau(false);
            loadNV();
            loadMK();
        }
    }//GEN-LAST:event_jPanel1HierarchyChanged

    private void rd_showActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rd_showActionPerformed
        // TODO add your handling code here:
        if (rd_show.isSelected()) {
            //show mật khẩu 
            pw_old.setEchoChar((char)0); 
            pw_new.setEchoChar((char)0); 
            pw_new2.setEchoChar((char)0); 
        } else {
            pw_old.setEchoChar('*');  
            pw_new.setEchoChar('*');
            pw_new2.setEchoChar('*');
        }
    }//GEN-LAST:event_rd_showActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GD_ThongTinCaNhan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GD_ThongTinCaNhan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GD_ThongTinCaNhan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GD_ThongTinCaNhan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GD_ThongTinCaNhan().setVisible(true);
            }
        });
    }
    private boolean validateInputNhanVien() {
        String ten = tf_name.getText().trim();
        Date ngaysinh = datechooser_ngaySinh.getDate();
        String cmnd = tf_cmnd.getText().trim();
        String diachi = tf_diaChi.getText().trim();
        String phone = tf_phone.getText().trim();
        String gmail = tf_gmail.getText().trim();
        
        if (ten.isEmpty()) {
            showRegexError(tf_name, "Tên không được rỗng");
            return false;
        }
        if (ten.length() > 30) {
            showRegexError(tf_name, "Tên không được quá 30 kí tự");
            return false;
        }
        if (!ten.matches("^[A-ZÀ-Ỹ][a-zà-ỹ]+(\\s[A-ZÀ-Ỹ][a-zà-ỹ]+)+$")) {
            showRegexError(tf_name, "Mỗi kí tự đầu của từ phải viết Hoa, không bao gồm chữ số và kí tự đặc biệt");
            return false;
        }
        if (ngaysinh == null) {
            JOptionPane.showMessageDialog(null, "Phải chọn ngày sinh", "Lỗi", JOptionPane.ERROR_MESSAGE);
            return false;
        }
        SimpleDateFormat date = new SimpleDateFormat("yyy-MM-dd");
        String d = date.format(ngaysinh);
        LocalDate namsinh = LocalDate.parse(d);
        if (LocalDate.now().getYear() - namsinh.getYear() < 18) {
            JOptionPane.showMessageDialog(null, "Phải từ 18 tuổi trở lên", "Lỗi", JOptionPane.ERROR_MESSAGE);
            return false;
        }
        if (cmnd.isEmpty()) {
            showRegexError(tf_cmnd, "CMND không được rỗng");
            return false;
        }
        if (!cmnd.matches("^0\\d{11}$")) {
            showRegexError(tf_cmnd, "CMND bắt đầu bằng số 0, phải đủ 12 chữ số");
            return false;
        }
        if (diachi.isEmpty()) {
            showRegexError(tf_diaChi, "Địa chỉ không được rỗng");
            return false;
        }
        if (phone.isEmpty()) {
            showRegexError(tf_phone, "Vui lòng nhập số điện thoại");
            return false;
        }
        if (!phone.matches("^0[1-9]\\d{8}$")) {
            showRegexError(tf_phone, "Số điện thoại bắt đầu bằng chữ số 0 và có tối đa 10 chữ số");
            return false;
        }
        ArrayList<NhanVien> ds = daonv.getAll(NhanVien.class);
        for (NhanVien i : ds) {
            if (!i.equals(GD_DangNhap.taiKhoan.getNhanVien()) && i.getSoDienThoai().equals(phone)) {
                JOptionPane.showMessageDialog(null, "Số điện thoại không được trùng", "Lỗi", JOptionPane.ERROR_MESSAGE);
                return false;
            }
        }
        if (gmail.isEmpty()) {
            showRegexError(tf_gmail, "Gmail không được rỗng");
            return false;
        }
        if (!gmail.matches("^[a-zA-Z0-9.]+@gmail\\.com$")) {
            showRegexError(tf_gmail, "Tên gmail chứa số, các chữ cái từ a - z, không chứa kí tự đặc biệt và tên miền phải là @gmail.com");
            return false;
        }
        return true;
    }
    private boolean validateInputMK() {
        String pw = String.valueOf(pw_new.getPassword());
        String pw2 = String.valueOf(pw_new2.getPassword());
        if (pw.isEmpty()) {
            showRegexError(pw_new, "Vui lòng nhập mật khẩu mới");
            return false;
        }
        if (!pw.matches("^(?=.*[a-z])(?=.*[A-Z])(?=.*\\d)(?=.*[@$#!%*?&])[A-Za-z\\d@$#!%*?&]{6,}$")) { // (?=...x) tìm chuỗi đứng trước x, "..." là định dạng khớp vs chuỗi cần tìm
            showRegexError(pw_new, "Mật khẩu có ít nhất 6 kí tự, bao gồm chữ Hoa, chữ thường, chữ số và kí tự đặc biệt");
            return false;
        }
        if (!pw2.equals(pw)) {
            showRegexError(pw_new2, "Mật khẩu vừa nhập không khớp với mật khẩu mới");
            return false;
        }
        return true;
    }
    private void moNhapLieuNhanVien(boolean b) {
        tf_name.setEditable(b);
        datechooser_ngaySinh.setEnabled(b);
        cb_gioiTinh.setEnabled(b);
        tf_cmnd.setEditable(b);
        tf_diaChi.setEditable(b);
        tf_phone.setEditable(b);
        tf_gmail.setEditable(b);
        cb_ca.setEnabled(b);
    }
    private void moNhapLieuMatKhau(boolean b) {
        pw_new.setEditable(b);
        pw_new2.setEditable(b);
    }
    private void loadNV() {
        if (GD_DangNhap.taiKhoan.getNhanVien() != null) {
            NhanVien a = I_CRUD.findById(GD_DangNhap.taiKhoan.getNhanVien().getMaNhanVien(), new NhanVien());
            tf_name.setText(a.getTenNhanVien());
            try {
                datechooser_ngaySinh.setDate(new SimpleDateFormat("yyyy-MM-dd").parse(a.getNgaySinh().toString()));
            } catch (ParseException ex) {
                Logger.getLogger(GD_ThongTinCaNhan.class.getName()).log(Level.SEVERE, null, ex);
            }
            cb_gioiTinh.setSelectedItem((a.getGioiTinh()? "Nam" : "Nữ"));
            tf_cmnd.setText(a.getCmnd());
            tf_diaChi.setText(a.getDiaChi());
            tf_phone.setText(a.getSoDienThoai());
            tf_gmail.setText(a.getGmail());
            cb_ca.setSelectedItem(a.getCa().getTenCa());
        }
    }
    private void loadMK() {
        if (GD_DangNhap.taiKhoan.getNhanVien()!= null) {
//            TaiKhoan a = I_CRUD.findById(GD_DangNhap.taiKhoan.getTenTaiKhoan(), new TaiKhoan()); // tìm kiếm trên tenTK, khi tenTK bị đổi thì tìm ko dc
            TaiKhoan a = daotk.findByNV(GD_DangNhap.taiKhoan.getNhanVien().getMaNhanVien());
            
            pw_old.setText(a.getMatKhau());
            
        }
        pw_new.setText("");
        pw_new2.setText("");
    }
    private DAO_NhanVien daonv = new DAO_NhanVien();
    private DAO_TaiKhoan daotk = new DAO_TaiKhoan();
    private DAO_Ca daoca = new DAO_Ca();
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_edit_mk;
    private javax.swing.JButton btn_edit_nhanvien;
    private javax.swing.JButton btn_luu_mk;
    private javax.swing.JButton btn_luu_nhanvien;
    private javax.swing.JComboBox<String> cb_ca;
    private javax.swing.JComboBox<String> cb_gioiTinh;
    private com.toedter.calendar.JDateChooser datechooser_ngaySinh;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel14;
    private javax.swing.JPanel jPanel15;
    private javax.swing.JPanel jPanel16;
    private javax.swing.JPanel jPanel17;
    private javax.swing.JPanel jPanel18;
    private javax.swing.JPanel jPanel19;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel20;
    private javax.swing.JPanel jPanel21;
    private javax.swing.JPanel jPanel22;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JPasswordField pw_new;
    private javax.swing.JPasswordField pw_new2;
    private javax.swing.JPasswordField pw_old;
    private javax.swing.JRadioButton rd_show;
    private javax.swing.JTextField tf_cmnd;
    private javax.swing.JTextField tf_diaChi;
    private javax.swing.JTextField tf_gmail;
    private javax.swing.JTextField tf_name;
    private javax.swing.JTextField tf_phone;
    // End of variables declaration//GEN-END:variables
}
