package gui;


import java.awt.BorderLayout;
import java.awt.Color;
import java.awt.Dimension;
import org.jfree.chart.ChartFactory;
import org.jfree.chart.ChartPanel;
import org.jfree.chart.JFreeChart;
import org.jfree.chart.axis.NumberAxis;
import org.jfree.chart.axis.SymbolAxis;
import org.jfree.chart.plot.PiePlot;
import org.jfree.chart.plot.XYPlot;
import org.jfree.chart.renderer.xy.XYSplineRenderer;
import org.jfree.data.general.DefaultPieDataset;
import org.jfree.data.xy.XYDataset;
import org.jfree.data.xy.XYSeries;
import org.jfree.data.xy.XYSeriesCollection;


/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author Admin
 */
public class GD_Thongke extends javax.swing.JFrame {

    /**
     * Creates new form GD
     */
    public GD_Thongke() {
        initComponents();
        display();
        this.setBackground(Color.white);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        panel_TongDoanhThu = new javax.swing.JPanel();
        tongDoanhThu = new javax.swing.JLabel();
        line1 = new javax.swing.JPanel();
        line2 = new javax.swing.JPanel();
        doanhThuTheoNam = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        comboBoxDoanhThu = new rojerusan.RSComboMetro();
        tongDoanhThuPhong = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        textTongDoanhThuPhong = new javax.swing.JLabel();
        tongDoanhThuDichVu = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        textTongDoanhThuDichVu = new javax.swing.JLabel();
        tongSoHoaDon = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        textTongSoHoaDon = new javax.swing.JLabel();
        tongSoDichVu = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        textTongSoDichVu = new javax.swing.JLabel();
        chart = new javax.swing.JPanel();
        panel_SoSanh = new javax.swing.JPanel();
        tongDoanhThu1 = new javax.swing.JLabel();
        panel_soSanhDoanhThuTheoNam = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        comboBoxSoSanh = new rojerusan.RSComboMetro();
        line3 = new javax.swing.JPanel();
        panel_Chart_SoSanh = new javax.swing.JPanel();
        line4 = new javax.swing.JPanel();
        soSanh = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        panel_doanhThuSoSanhPhong = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        textDoanhThuSoSanhPhong = new javax.swing.JLabel();
        iconDoanhThuSoSanhPhong = new javax.swing.JLabel();
        panel_doanhThuSoSanhPhong2 = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        textDoanhThuSoSanhPhong2 = new javax.swing.JLabel();
        iconDoanhThuSoSanhPhong2 = new javax.swing.JLabel();
        panel_doanhThuSoSanhPhong3 = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        textDoanhThuSoSanhPhong3 = new javax.swing.JLabel();
        iconDoanhThuSoSanhPhong3 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        setMinimumSize(new java.awt.Dimension(1920, 964));

        panel_TongDoanhThu.setBackground(new java.awt.Color(255, 255, 255));
        panel_TongDoanhThu.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        panel_TongDoanhThu.setMaximumSize(new java.awt.Dimension(475, 440));
        panel_TongDoanhThu.setMinimumSize(new java.awt.Dimension(475, 440));
        panel_TongDoanhThu.setName(""); // NOI18N
        panel_TongDoanhThu.setPreferredSize(new java.awt.Dimension(475, 440));
        panel_TongDoanhThu.setLayout(new java.awt.GridBagLayout());

        tongDoanhThu.setFont(new java.awt.Font("Segoe UI Black", 1, 24)); // NOI18N
        tongDoanhThu.setText("TỔNG DOANH THU");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = java.awt.GridBagConstraints.REMAINDER;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTH;
        panel_TongDoanhThu.add(tongDoanhThu, gridBagConstraints);

        line1.setBackground(new java.awt.Color(102, 102, 102));
        line1.setMaximumSize(new java.awt.Dimension(462, 2));
        line1.setMinimumSize(new java.awt.Dimension(462, 2));
        line1.setPreferredSize(new java.awt.Dimension(462, 2));

        javax.swing.GroupLayout line1Layout = new javax.swing.GroupLayout(line1);
        line1.setLayout(line1Layout);
        line1Layout.setHorizontalGroup(
            line1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        line1Layout.setVerticalGroup(
            line1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 2, Short.MAX_VALUE)
        );

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.gridwidth = java.awt.GridBagConstraints.REMAINDER;
        gridBagConstraints.insets = new java.awt.Insets(22, 0, 0, 0);
        panel_TongDoanhThu.add(line1, gridBagConstraints);

        line2.setBackground(new java.awt.Color(102, 102, 102));
        line2.setMaximumSize(new java.awt.Dimension(462, 2));
        line2.setMinimumSize(new java.awt.Dimension(462, 2));
        line2.setPreferredSize(new java.awt.Dimension(462, 2));
        line2.setVerifyInputWhenFocusTarget(false);

        javax.swing.GroupLayout line2Layout = new javax.swing.GroupLayout(line2);
        line2.setLayout(line2Layout);
        line2Layout.setHorizontalGroup(
            line2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 462, Short.MAX_VALUE)
        );
        line2Layout.setVerticalGroup(
            line2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 2, Short.MAX_VALUE)
        );

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.gridwidth = java.awt.GridBagConstraints.REMAINDER;
        panel_TongDoanhThu.add(line2, gridBagConstraints);

        doanhThuTheoNam.setBackground(new java.awt.Color(255, 255, 255));
        doanhThuTheoNam.setMaximumSize(new java.awt.Dimension(418, 53));
        doanhThuTheoNam.setMinimumSize(new java.awt.Dimension(418, 53));
        doanhThuTheoNam.setLayout(new javax.swing.BoxLayout(doanhThuTheoNam, javax.swing.BoxLayout.LINE_AXIS));

        jLabel2.setFont(new java.awt.Font("Segoe UI Black", 1, 18)); // NOI18N
        jLabel2.setText("Doanh thu theo năm:");
        jLabel2.setMaximumSize(new java.awt.Dimension(9999, 9999));
        jLabel2.setMinimumSize(new java.awt.Dimension(1, 1));
        jLabel2.setPreferredSize(new java.awt.Dimension(200, 30));
        doanhThuTheoNam.add(jLabel2);

        comboBoxDoanhThu.setForeground(new java.awt.Color(0, 0, 0));
        comboBoxDoanhThu.setColorBorde(new java.awt.Color(0, 0, 0));
        comboBoxDoanhThu.setColorFondo(new java.awt.Color(255, 255, 255));
        comboBoxDoanhThu.setMaximumSize(new java.awt.Dimension(250, 30));
        comboBoxDoanhThu.setMinimumSize(new java.awt.Dimension(150, 30));
        comboBoxDoanhThu.setPreferredSize(new java.awt.Dimension(200, 30));
        doanhThuTheoNam.add(comboBoxDoanhThu);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = java.awt.GridBagConstraints.REMAINDER;
        gridBagConstraints.insets = new java.awt.Insets(24, 0, 0, 0);
        panel_TongDoanhThu.add(doanhThuTheoNam, gridBagConstraints);

        tongDoanhThuPhong.setBackground(new java.awt.Color(255, 255, 255));
        tongDoanhThuPhong.setMaximumSize(new java.awt.Dimension(418, 53));
        tongDoanhThuPhong.setMinimumSize(new java.awt.Dimension(418, 53));
        tongDoanhThuPhong.setPreferredSize(new java.awt.Dimension(418, 53));
        tongDoanhThuPhong.setLayout(new java.awt.BorderLayout());

        jLabel3.setFont(new java.awt.Font("Segoe UI Black", 1, 18)); // NOI18N
        jLabel3.setText("Tổng doanh thu phòng:");
        jLabel3.setMaximumSize(new java.awt.Dimension(9999, 9999));
        jLabel3.setMinimumSize(new java.awt.Dimension(1, 1));
        jLabel3.setPreferredSize(new java.awt.Dimension(220, 30));
        tongDoanhThuPhong.add(jLabel3, java.awt.BorderLayout.WEST);

        textTongDoanhThuPhong.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        textTongDoanhThuPhong.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        textTongDoanhThuPhong.setText("150.000.000.000Đ");
        textTongDoanhThuPhong.setMaximumSize(new java.awt.Dimension(9999, 9999));
        textTongDoanhThuPhong.setMinimumSize(new java.awt.Dimension(1, 1));
        textTongDoanhThuPhong.setPreferredSize(new java.awt.Dimension(190, 30));
        tongDoanhThuPhong.add(textTongDoanhThuPhong, java.awt.BorderLayout.EAST);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 7;
        gridBagConstraints.gridwidth = java.awt.GridBagConstraints.REMAINDER;
        panel_TongDoanhThu.add(tongDoanhThuPhong, gridBagConstraints);

        tongDoanhThuDichVu.setBackground(new java.awt.Color(255, 255, 255));
        tongDoanhThuDichVu.setMaximumSize(new java.awt.Dimension(418, 53));
        tongDoanhThuDichVu.setMinimumSize(new java.awt.Dimension(418, 53));
        tongDoanhThuDichVu.setPreferredSize(new java.awt.Dimension(418, 53));
        tongDoanhThuDichVu.setLayout(new java.awt.BorderLayout());

        jLabel9.setFont(new java.awt.Font("Segoe UI Black", 1, 18)); // NOI18N
        jLabel9.setText("Tổng doanh dịch vụ:");
        jLabel9.setMaximumSize(new java.awt.Dimension(9999, 9999));
        jLabel9.setMinimumSize(new java.awt.Dimension(1, 1));
        jLabel9.setPreferredSize(new java.awt.Dimension(220, 30));
        tongDoanhThuDichVu.add(jLabel9, java.awt.BorderLayout.WEST);

        textTongDoanhThuDichVu.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        textTongDoanhThuDichVu.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        textTongDoanhThuDichVu.setText("150.000.000.000Đ");
        textTongDoanhThuDichVu.setMaximumSize(new java.awt.Dimension(9999, 9999));
        textTongDoanhThuDichVu.setMinimumSize(new java.awt.Dimension(1, 1));
        textTongDoanhThuDichVu.setPreferredSize(new java.awt.Dimension(190, 30));
        tongDoanhThuDichVu.add(textTongDoanhThuDichVu, java.awt.BorderLayout.EAST);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.gridwidth = java.awt.GridBagConstraints.REMAINDER;
        gridBagConstraints.insets = new java.awt.Insets(17, 0, 0, 0);
        panel_TongDoanhThu.add(tongDoanhThuDichVu, gridBagConstraints);

        tongSoHoaDon.setBackground(new java.awt.Color(255, 255, 255));
        tongSoHoaDon.setMaximumSize(new java.awt.Dimension(418, 53));
        tongSoHoaDon.setMinimumSize(new java.awt.Dimension(418, 53));
        tongSoHoaDon.setPreferredSize(new java.awt.Dimension(418, 53));
        tongSoHoaDon.setLayout(new java.awt.BorderLayout());

        jLabel10.setFont(new java.awt.Font("Segoe UI Black", 1, 18)); // NOI18N
        jLabel10.setText("Tổng số hóa đơn:");
        jLabel10.setMaximumSize(new java.awt.Dimension(9999, 9999));
        jLabel10.setMinimumSize(new java.awt.Dimension(1, 1));
        jLabel10.setPreferredSize(new java.awt.Dimension(220, 30));
        tongSoHoaDon.add(jLabel10, java.awt.BorderLayout.WEST);

        textTongSoHoaDon.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        textTongSoHoaDon.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        textTongSoHoaDon.setText("30");
        textTongSoHoaDon.setMaximumSize(new java.awt.Dimension(9999, 9999));
        textTongSoHoaDon.setMinimumSize(new java.awt.Dimension(1, 1));
        textTongSoHoaDon.setPreferredSize(new java.awt.Dimension(190, 30));
        tongSoHoaDon.add(textTongSoHoaDon, java.awt.BorderLayout.EAST);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.gridwidth = java.awt.GridBagConstraints.REMAINDER;
        gridBagConstraints.insets = new java.awt.Insets(24, 0, 0, 0);
        panel_TongDoanhThu.add(tongSoHoaDon, gridBagConstraints);

        tongSoDichVu.setBackground(new java.awt.Color(255, 255, 255));
        tongSoDichVu.setMaximumSize(new java.awt.Dimension(418, 53));
        tongSoDichVu.setMinimumSize(new java.awt.Dimension(418, 53));
        tongSoDichVu.setPreferredSize(new java.awt.Dimension(418, 53));
        tongSoDichVu.setLayout(new java.awt.BorderLayout());

        jLabel11.setFont(new java.awt.Font("Segoe UI Black", 1, 18)); // NOI18N
        jLabel11.setText("Tổng số dịch vụ:");
        jLabel11.setMaximumSize(new java.awt.Dimension(9999, 9999));
        jLabel11.setMinimumSize(new java.awt.Dimension(1, 1));
        jLabel11.setPreferredSize(new java.awt.Dimension(220, 30));
        tongSoDichVu.add(jLabel11, java.awt.BorderLayout.WEST);

        textTongSoDichVu.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        textTongSoDichVu.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        textTongSoDichVu.setText("15");
        textTongSoDichVu.setMaximumSize(new java.awt.Dimension(9999, 9999));
        textTongSoDichVu.setMinimumSize(new java.awt.Dimension(1, 1));
        textTongSoDichVu.setPreferredSize(new java.awt.Dimension(190, 30));
        tongSoDichVu.add(textTongSoDichVu, java.awt.BorderLayout.EAST);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.gridwidth = java.awt.GridBagConstraints.REMAINDER;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 23, 0);
        panel_TongDoanhThu.add(tongSoDichVu, gridBagConstraints);

        chart.setBackground(new java.awt.Color(255, 255, 255));
        chart.setMaximumSize(new java.awt.Dimension(1427, 440));
        chart.setMinimumSize(new java.awt.Dimension(0, 0));
        chart.setPreferredSize(new java.awt.Dimension(0, 0));
        chart.setLayout(new java.awt.BorderLayout());

        panel_SoSanh.setBackground(new java.awt.Color(255, 255, 255));
        panel_SoSanh.setMaximumSize(new java.awt.Dimension(475, 506));
        panel_SoSanh.setMinimumSize(new java.awt.Dimension(475, 506));

        tongDoanhThu1.setFont(new java.awt.Font("Segoe UI Black", 1, 24)); // NOI18N
        tongDoanhThu1.setText("SO SÁNH");

        panel_soSanhDoanhThuTheoNam.setBackground(new java.awt.Color(255, 255, 255));
        panel_soSanhDoanhThuTheoNam.setMaximumSize(new java.awt.Dimension(418, 53));
        panel_soSanhDoanhThuTheoNam.setMinimumSize(new java.awt.Dimension(418, 53));
        panel_soSanhDoanhThuTheoNam.setLayout(new javax.swing.BoxLayout(panel_soSanhDoanhThuTheoNam, javax.swing.BoxLayout.LINE_AXIS));

        jLabel4.setFont(new java.awt.Font("Segoe UI Black", 1, 18)); // NOI18N
        jLabel4.setText("Doanh thu theo năm:");
        jLabel4.setMaximumSize(new java.awt.Dimension(9999, 9999));
        jLabel4.setMinimumSize(new java.awt.Dimension(1, 1));
        jLabel4.setPreferredSize(new java.awt.Dimension(200, 30));
        panel_soSanhDoanhThuTheoNam.add(jLabel4);

        comboBoxSoSanh.setForeground(new java.awt.Color(0, 0, 0));
        comboBoxSoSanh.setColorBorde(new java.awt.Color(0, 0, 0));
        comboBoxSoSanh.setColorFondo(new java.awt.Color(255, 255, 255));
        comboBoxSoSanh.setMaximumSize(new java.awt.Dimension(250, 30));
        comboBoxSoSanh.setMinimumSize(new java.awt.Dimension(150, 30));
        comboBoxSoSanh.setPreferredSize(new java.awt.Dimension(200, 30));
        comboBoxSoSanh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboBoxSoSanhActionPerformed(evt);
            }
        });
        panel_soSanhDoanhThuTheoNam.add(comboBoxSoSanh);

        line3.setBackground(new java.awt.Color(102, 102, 102));
        line3.setMaximumSize(new java.awt.Dimension(462, 2));
        line3.setMinimumSize(new java.awt.Dimension(462, 2));

        javax.swing.GroupLayout line3Layout = new javax.swing.GroupLayout(line3);
        line3.setLayout(line3Layout);
        line3Layout.setHorizontalGroup(
            line3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 474, Short.MAX_VALUE)
        );
        line3Layout.setVerticalGroup(
            line3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout panel_Chart_SoSanhLayout = new javax.swing.GroupLayout(panel_Chart_SoSanh);
        panel_Chart_SoSanh.setLayout(panel_Chart_SoSanhLayout);
        panel_Chart_SoSanhLayout.setHorizontalGroup(
            panel_Chart_SoSanhLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        panel_Chart_SoSanhLayout.setVerticalGroup(
            panel_Chart_SoSanhLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 212, Short.MAX_VALUE)
        );

        line4.setBackground(new java.awt.Color(102, 102, 102));
        line4.setMaximumSize(new java.awt.Dimension(462, 2));
        line4.setMinimumSize(new java.awt.Dimension(462, 2));

        javax.swing.GroupLayout line4Layout = new javax.swing.GroupLayout(line4);
        line4.setLayout(line4Layout);
        line4Layout.setHorizontalGroup(
            line4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 474, Short.MAX_VALUE)
        );
        line4Layout.setVerticalGroup(
            line4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        soSanh.setBackground(new java.awt.Color(255, 255, 255));
        soSanh.setLayout(new java.awt.GridBagLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI Black", 1, 24)); // NOI18N
        jLabel1.setText("2023 -> 2024");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        soSanh.add(jLabel1, gridBagConstraints);

        panel_doanhThuSoSanhPhong.setBackground(new java.awt.Color(255, 255, 255));
        panel_doanhThuSoSanhPhong.setMaximumSize(new java.awt.Dimension(418, 30));
        panel_doanhThuSoSanhPhong.setMinimumSize(new java.awt.Dimension(418, 30));
        panel_doanhThuSoSanhPhong.setPreferredSize(new java.awt.Dimension(418, 30));
        panel_doanhThuSoSanhPhong.setLayout(new java.awt.GridBagLayout());

        jLabel12.setFont(new java.awt.Font("Segoe UI Black", 1, 18)); // NOI18N
        jLabel12.setText("Doanh thu Phòng:");
        jLabel12.setMaximumSize(new java.awt.Dimension(9999, 9999));
        jLabel12.setMinimumSize(new java.awt.Dimension(1, 1));
        jLabel12.setPreferredSize(new java.awt.Dimension(184, 30));
        panel_doanhThuSoSanhPhong.add(jLabel12, new java.awt.GridBagConstraints());

        textDoanhThuSoSanhPhong.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        textDoanhThuSoSanhPhong.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        textDoanhThuSoSanhPhong.setText("20%");
        textDoanhThuSoSanhPhong.setMaximumSize(new java.awt.Dimension(9999, 9999));
        textDoanhThuSoSanhPhong.setMinimumSize(new java.awt.Dimension(1, 1));
        textDoanhThuSoSanhPhong.setPreferredSize(new java.awt.Dimension(190, 30));
        panel_doanhThuSoSanhPhong.add(textDoanhThuSoSanhPhong, new java.awt.GridBagConstraints());

        iconDoanhThuSoSanhPhong.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8-up-20.png"))); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.insets = new java.awt.Insets(0, 6, 0, 0);
        panel_doanhThuSoSanhPhong.add(iconDoanhThuSoSanhPhong, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(6, 0, 0, 0);
        soSanh.add(panel_doanhThuSoSanhPhong, gridBagConstraints);

        panel_doanhThuSoSanhPhong2.setBackground(new java.awt.Color(255, 255, 255));
        panel_doanhThuSoSanhPhong2.setMaximumSize(new java.awt.Dimension(418, 30));
        panel_doanhThuSoSanhPhong2.setMinimumSize(new java.awt.Dimension(418, 30));
        panel_doanhThuSoSanhPhong2.setPreferredSize(new java.awt.Dimension(418, 30));
        panel_doanhThuSoSanhPhong2.setLayout(new java.awt.GridBagLayout());

        jLabel13.setFont(new java.awt.Font("Segoe UI Black", 1, 18)); // NOI18N
        jLabel13.setText("Doanh thu Dịch Vụ:");
        jLabel13.setMaximumSize(new java.awt.Dimension(9999, 9999));
        jLabel13.setMinimumSize(new java.awt.Dimension(1, 1));
        jLabel13.setPreferredSize(new java.awt.Dimension(184, 30));
        panel_doanhThuSoSanhPhong2.add(jLabel13, new java.awt.GridBagConstraints());

        textDoanhThuSoSanhPhong2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        textDoanhThuSoSanhPhong2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        textDoanhThuSoSanhPhong2.setText("15%");
        textDoanhThuSoSanhPhong2.setMaximumSize(new java.awt.Dimension(9999, 9999));
        textDoanhThuSoSanhPhong2.setMinimumSize(new java.awt.Dimension(1, 1));
        textDoanhThuSoSanhPhong2.setPreferredSize(new java.awt.Dimension(190, 30));
        panel_doanhThuSoSanhPhong2.add(textDoanhThuSoSanhPhong2, new java.awt.GridBagConstraints());

        iconDoanhThuSoSanhPhong2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8-down-20.png"))); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.insets = new java.awt.Insets(0, 6, 0, 0);
        panel_doanhThuSoSanhPhong2.add(iconDoanhThuSoSanhPhong2, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(6, 0, 0, 0);
        soSanh.add(panel_doanhThuSoSanhPhong2, gridBagConstraints);

        panel_doanhThuSoSanhPhong3.setBackground(new java.awt.Color(255, 255, 255));
        panel_doanhThuSoSanhPhong3.setMaximumSize(new java.awt.Dimension(418, 30));
        panel_doanhThuSoSanhPhong3.setMinimumSize(new java.awt.Dimension(418, 30));
        panel_doanhThuSoSanhPhong3.setPreferredSize(new java.awt.Dimension(418, 30));
        panel_doanhThuSoSanhPhong3.setLayout(new java.awt.GridBagLayout());

        jLabel14.setFont(new java.awt.Font("Segoe UI Black", 1, 18)); // NOI18N
        jLabel14.setText("Tổng doanh thu");
        jLabel14.setMaximumSize(new java.awt.Dimension(9999, 9999));
        jLabel14.setMinimumSize(new java.awt.Dimension(1, 1));
        jLabel14.setPreferredSize(new java.awt.Dimension(184, 30));
        panel_doanhThuSoSanhPhong3.add(jLabel14, new java.awt.GridBagConstraints());

        textDoanhThuSoSanhPhong3.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        textDoanhThuSoSanhPhong3.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        textDoanhThuSoSanhPhong3.setText("22%");
        textDoanhThuSoSanhPhong3.setMaximumSize(new java.awt.Dimension(9999, 9999));
        textDoanhThuSoSanhPhong3.setMinimumSize(new java.awt.Dimension(1, 1));
        textDoanhThuSoSanhPhong3.setPreferredSize(new java.awt.Dimension(190, 30));
        panel_doanhThuSoSanhPhong3.add(textDoanhThuSoSanhPhong3, new java.awt.GridBagConstraints());

        iconDoanhThuSoSanhPhong3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8-horizontal-line-20.png"))); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.insets = new java.awt.Insets(0, 6, 0, 0);
        panel_doanhThuSoSanhPhong3.add(iconDoanhThuSoSanhPhong3, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(6, 0, 0, 0);
        soSanh.add(panel_doanhThuSoSanhPhong3, gridBagConstraints);

        javax.swing.GroupLayout panel_SoSanhLayout = new javax.swing.GroupLayout(panel_SoSanh);
        panel_SoSanh.setLayout(panel_SoSanhLayout);
        panel_SoSanhLayout.setHorizontalGroup(
            panel_SoSanhLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_SoSanhLayout.createSequentialGroup()
                .addGroup(panel_SoSanhLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panel_SoSanhLayout.createSequentialGroup()
                        .addGroup(panel_SoSanhLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(panel_SoSanhLayout.createSequentialGroup()
                                .addGap(177, 177, 177)
                                .addComponent(tongDoanhThu1))
                            .addGroup(panel_SoSanhLayout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(line3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(panel_SoSanhLayout.createSequentialGroup()
                                .addGap(35, 35, 35)
                                .addComponent(panel_soSanhDoanhThuTheoNam, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(panel_SoSanhLayout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(panel_Chart_SoSanh, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(panel_SoSanhLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(panel_SoSanhLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(line4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(soSanh, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap())
        );
        panel_SoSanhLayout.setVerticalGroup(
            panel_SoSanhLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_SoSanhLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(tongDoanhThu1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panel_soSanhDoanhThuTheoNam, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(line3, javax.swing.GroupLayout.PREFERRED_SIZE, 1, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panel_Chart_SoSanh, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(line4, javax.swing.GroupLayout.PREFERRED_SIZE, 1, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(soSanh, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jPanel4.setBackground(new java.awt.Color(153, 0, 0));
        jPanel4.setMaximumSize(new java.awt.Dimension(670, 509));
        jPanel4.setMinimumSize(new java.awt.Dimension(670, 509));
        jPanel4.setPreferredSize(new java.awt.Dimension(670, 509));

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 726, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jPanel5.setBackground(new java.awt.Color(153, 0, 0));
        jPanel5.setMaximumSize(new java.awt.Dimension(670, 509));
        jPanel5.setMinimumSize(new java.awt.Dimension(670, 509));

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 695, Short.MAX_VALUE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(panel_TongDoanhThu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(panel_SoSanh, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(6, 6, 6)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, 726, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(chart, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(panel_TongDoanhThu, javax.swing.GroupLayout.PREFERRED_SIZE, 402, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(chart, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jPanel5, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 466, Short.MAX_VALUE)
                            .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, 466, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(panel_SoSanh, javax.swing.GroupLayout.PREFERRED_SIZE, 466, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void comboBoxSoSanhActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboBoxSoSanhActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_comboBoxSoSanhActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GD_Thongke.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GD_Thongke.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GD_Thongke.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GD_Thongke.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GD_Thongke().setVisible(true);
            }
        });
    }
    
        private void display() {
        XYSeries series = new XYSeries("Frequency");
        series.add(0, 1);
        series.add(1, 1);
        series.add(2, 3);
        series.add(3, 7);
        series.add(4, 11);
        series.add(5, 21);
        series.add(6, 150);
        series.add(7, 16);
        series.add(8, 22);
        series.add(9, 7);
        series.add(10, 1);
        series.add(11, 2);
        XYDataset dataset = new XYSeriesCollection(series);
        String[] labels = new String[series.getItemCount()];
        labels[0] = "1";
        labels[1] = "2";
        labels[2] = "3";
        labels[3] = "4";
        labels[4] = "5";
        labels[5] = "6";
        labels[6] = "7";
        labels[7] = "8";
        labels[8] = "9";
        labels[9] = "10";
        labels[10] = "11";
        labels[11] = "12";
        NumberAxis domain = new SymbolAxis("X", labels);
        NumberAxis range = new NumberAxis("Y");
        XYSplineRenderer r = new XYSplineRenderer(8);
        XYPlot xyplot = new XYPlot(dataset, domain, range, r);
        JFreeChart chart = new JFreeChart(xyplot);
        ChartPanel chartPanel = new ChartPanel(chart) {

            @Override
            public Dimension getPreferredSize() {
                return new Dimension(1427, 440);
            }
        };
        this.chart.add(chartPanel, BorderLayout.WEST);
    }
        
        public void showPieChart(){
        
        //create dataset
      DefaultPieDataset barDataset = new DefaultPieDataset();
      barDataset.setValue("IPhone 5s" , Double.valueOf(20));  
      barDataset.setValue("SamSung Grand" , Double.valueOf(20));   
      barDataset.setValue("MotoG" , Double.valueOf(40));    
      barDataset.setValue("Nokia Lumia" , Double.valueOf(10));  
      
      //create chart
       JFreeChart piechart = ChartFactory.createPieChart("mobile sales",barDataset, false,true,false);//explain
      
        PiePlot piePlot =(PiePlot) piechart.getPlot();
      
       //changing pie chart blocks colors
       piePlot.setSectionPaint("IPhone 5s", new Color(255,255,102));
        piePlot.setSectionPaint("SamSung Grand", new Color(102,255,102));
        piePlot.setSectionPaint("MotoG", new Color(255,102,153));
        piePlot.setSectionPaint("Nokia Lumia", new Color(0,204,204));
      
       
        piePlot.setBackgroundPaint(Color.white);
        
        //create chartPanel to display chart(graph)
        ChartPanel barChartPanel = new ChartPanel(piechart);
        chart.removeAll();
        chart.add(barChartPanel, BorderLayout.WEST);
        chart.validate();
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel chart;
    private rojerusan.RSComboMetro comboBoxDoanhThu;
    private rojerusan.RSComboMetro comboBoxSoSanh;
    private javax.swing.JPanel doanhThuTheoNam;
    private javax.swing.JLabel iconDoanhThuSoSanhPhong;
    private javax.swing.JLabel iconDoanhThuSoSanhPhong2;
    private javax.swing.JLabel iconDoanhThuSoSanhPhong3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel line1;
    private javax.swing.JPanel line2;
    private javax.swing.JPanel line3;
    private javax.swing.JPanel line4;
    private javax.swing.JPanel panel_Chart_SoSanh;
    private javax.swing.JPanel panel_SoSanh;
    private javax.swing.JPanel panel_TongDoanhThu;
    private javax.swing.JPanel panel_doanhThuSoSanhPhong;
    private javax.swing.JPanel panel_doanhThuSoSanhPhong2;
    private javax.swing.JPanel panel_doanhThuSoSanhPhong3;
    private javax.swing.JPanel panel_soSanhDoanhThuTheoNam;
    private javax.swing.JPanel soSanh;
    private javax.swing.JLabel textDoanhThuSoSanhPhong;
    private javax.swing.JLabel textDoanhThuSoSanhPhong2;
    private javax.swing.JLabel textDoanhThuSoSanhPhong3;
    private javax.swing.JLabel textTongDoanhThuDichVu;
    private javax.swing.JLabel textTongDoanhThuPhong;
    private javax.swing.JLabel textTongSoDichVu;
    private javax.swing.JLabel textTongSoHoaDon;
    private javax.swing.JLabel tongDoanhThu;
    private javax.swing.JLabel tongDoanhThu1;
    private javax.swing.JPanel tongDoanhThuDichVu;
    private javax.swing.JPanel tongDoanhThuPhong;
    private javax.swing.JPanel tongSoDichVu;
    private javax.swing.JPanel tongSoHoaDon;
    // End of variables declaration//GEN-END:variables
}
