/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package gui;

import dao.DAO_PhieuDatPhong;
import entity.PhieuDatPhong;
import java.awt.Font;
import java.util.ArrayList;
import javax.swing.JLabel;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.JTableHeader;
import javax.swing.table.TableCellRenderer;

/**
 *
 * @author quang
 */
public class GD_TraCuu_PhieuDatPhong extends javax.swing.JFrame implements I_TraCuu_QuanLi<PhieuDatPhong>{

    /**
     * Creates new form GD_TraCuu_PhieuDatPhong
     */
    public GD_TraCuu_PhieuDatPhong() {
        initComponents();
        model = (DefaultTableModel) table_TraCuu.getModel();
        loadTable(daopdp.getAll(PhieuDatPhong.class), model);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlMain2 = new javax.swing.JPanel();
        pnlTop2 = new javax.swing.JPanel();
        pnlTop_title2 = new javax.swing.JLabel();
        pnlCenter2 = new javax.swing.JPanel();
        pnlThongTinTraCuu2 = new javax.swing.JPanel();
        lbl_TraCuu2 = new javax.swing.JLabel();
        tf_TraCuu2 = new javax.swing.JTextField();
        pnlData = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        table_TraCuu = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        pnlMain2.setPreferredSize(new java.awt.Dimension(1650, 964));
        pnlMain2.setLayout(new java.awt.BorderLayout());

        pnlTop2.setBackground(new java.awt.Color(255, 255, 255));
        pnlTop2.setPreferredSize(new java.awt.Dimension(828, 100));
        pnlTop2.setLayout(new java.awt.BorderLayout());

        pnlTop_title2.setBackground(new java.awt.Color(255, 255, 255));
        pnlTop_title2.setFont(new java.awt.Font("Segoe UI Black", 1, 30)); // NOI18N
        pnlTop_title2.setForeground(new java.awt.Color(40, 77, 133));
        pnlTop_title2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        pnlTop_title2.setText("TRA CỨU PHIẾU ĐẶT PHÒNG");
        pnlTop2.add(pnlTop_title2, java.awt.BorderLayout.CENTER);

        pnlMain2.add(pnlTop2, java.awt.BorderLayout.NORTH);

        pnlCenter2.setBackground(new java.awt.Color(255, 255, 255));

        pnlThongTinTraCuu2.setBackground(new java.awt.Color(255, 255, 255));

        lbl_TraCuu2.setFont(new java.awt.Font("Segoe UI Light", 0, 27)); // NOI18N
        lbl_TraCuu2.setForeground(new java.awt.Color(40, 77, 133));
        lbl_TraCuu2.setText("Nhập thông tin tra cứu:");

        tf_TraCuu2.setBackground(new java.awt.Color(142, 172, 207));
        tf_TraCuu2.setFont(new java.awt.Font("Segoe UI", 0, 27)); // NOI18N
        tf_TraCuu2.setToolTipText("");
        tf_TraCuu2.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 51, 153), 2, true));
        tf_TraCuu2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tf_TraCuu2KeyReleased(evt);
            }
        });

        javax.swing.GroupLayout pnlThongTinTraCuu2Layout = new javax.swing.GroupLayout(pnlThongTinTraCuu2);
        pnlThongTinTraCuu2.setLayout(pnlThongTinTraCuu2Layout);
        pnlThongTinTraCuu2Layout.setHorizontalGroup(
            pnlThongTinTraCuu2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlThongTinTraCuu2Layout.createSequentialGroup()
                .addGap(253, 253, 253)
                .addComponent(lbl_TraCuu2)
                .addGap(18, 18, 18)
                .addComponent(tf_TraCuu2, javax.swing.GroupLayout.PREFERRED_SIZE, 782, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlThongTinTraCuu2Layout.setVerticalGroup(
            pnlThongTinTraCuu2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlThongTinTraCuu2Layout.createSequentialGroup()
                .addContainerGap(20, Short.MAX_VALUE)
                .addGroup(pnlThongTinTraCuu2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lbl_TraCuu2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(tf_TraCuu2))
                .addGap(20, 20, 20))
        );

        pnlData.setBackground(new java.awt.Color(255, 255, 255));

        jScrollPane2.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_ALWAYS);
        jScrollPane2.setColumnHeaderView(null);

        table_TraCuu.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        table_TraCuu.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        table_TraCuu.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Mã phiếu", "Ngày tạo phiếu", "Ngày nhận phòng", "Trạng thái", "Giá cọc", "Nhân viên", "Khách hàng", "Phòng"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        table_TraCuu.setGridColor(new java.awt.Color(153, 153, 153));
        table_TraCuu.setRowHeight(30);
        table_TraCuu.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        table_TraCuu.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        table_TraCuu.getTableHeader().setReorderingAllowed(false);
        jScrollPane2.setViewportView(table_TraCuu);
        table_TraCuu.setRowHeight(35);
        // Chỉnh font cho header
        JTableHeader header = table_TraCuu.getTableHeader();
        header.setFont(new Font("Segoe UI", Font.PLAIN, 20));
        // Căn lề cho header
        TableCellRenderer rendererFromHeader = header.getDefaultRenderer();
        JLabel headerLabel = (JLabel) rendererFromHeader;
        headerLabel.setHorizontalAlignment(JLabel.CENTER);

        javax.swing.GroupLayout pnlDataLayout = new javax.swing.GroupLayout(pnlData);
        pnlData.setLayout(pnlDataLayout);
        pnlDataLayout.setHorizontalGroup(
            pnlDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlDataLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 1860, Short.MAX_VALUE)
                .addGap(30, 30, 30))
        );
        pnlDataLayout.setVerticalGroup(
            pnlDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlDataLayout.createSequentialGroup()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 753, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 24, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout pnlCenter2Layout = new javax.swing.GroupLayout(pnlCenter2);
        pnlCenter2.setLayout(pnlCenter2Layout);
        pnlCenter2Layout.setHorizontalGroup(
            pnlCenter2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlThongTinTraCuu2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(pnlData, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        pnlCenter2Layout.setVerticalGroup(
            pnlCenter2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlCenter2Layout.createSequentialGroup()
                .addComponent(pnlThongTinTraCuu2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnlData, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pnlMain2.add(pnlCenter2, java.awt.BorderLayout.CENTER);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlMain2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlMain2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tf_TraCuu2KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tf_TraCuu2KeyReleased
        // TODO add your handling code here:
        dspdp = daopdp.search(tf_TraCuu2.getText().trim(), PhieuDatPhong.class);
        loadTable(dspdp, model);
    }//GEN-LAST:event_tf_TraCuu2KeyReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GD_TraCuu_PhieuDatPhong.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GD_TraCuu_PhieuDatPhong.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GD_TraCuu_PhieuDatPhong.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GD_TraCuu_PhieuDatPhong.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GD_TraCuu_PhieuDatPhong().setVisible(true);
            }
        });
    }
       
    private DAO_PhieuDatPhong daopdp = new DAO_PhieuDatPhong();
    private ArrayList<PhieuDatPhong> dspdp = daopdp.getAll(PhieuDatPhong.class);
    private DefaultTableModel model;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lbl_TraCuu2;
    private javax.swing.JPanel pnlCenter2;
    private javax.swing.JPanel pnlData;
    private javax.swing.JPanel pnlMain2;
    private javax.swing.JPanel pnlThongTinTraCuu2;
    private javax.swing.JPanel pnlTop2;
    private javax.swing.JLabel pnlTop_title2;
    private javax.swing.JTable table_TraCuu;
    private javax.swing.JTextField tf_TraCuu2;
    // End of variables declaration//GEN-END:variables
}
