/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package gui;

import dao.DAO_ChiTietPhong_HoaDon;
import dao.DAO_Phong;
import dao.I_CRUD;
import entity.ChitTietPhongHoaDon;
import entity.HoaDon;
import entity.KhachHang;
import entity.Phong;
import java.awt.BorderLayout;
import java.awt.Color;
import java.awt.Dimension;
import java.awt.FlowLayout;
import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.ListSelectionModel;
import javax.swing.SingleSelectionModel;
import javax.swing.border.Border;
import javax.swing.border.LineBorder;
import javax.swing.table.DefaultTableModel;
import smallPanel.Panel_DanhSachPhongFullCol;
import smallPanel.Panel_Phong;

/**
 *
 * @author quang
 */
public class GD_XuLy_ChuyenPhong extends javax.swing.JFrame {

    private ListSelectionModel SingleSelectionModel;

    /**
     * Creates new form GD_ChuyenPhong
     */
    public GD_XuLy_ChuyenPhong() {
        initComponents();
        model = (DefaultTableModel) tbl_phongTrong.getModel();
        
        loadDSPhongDangSuDung();
//        loadDSPhongTrong();
        ArrayList<String> dsidKH = daoctp.getMaKHtheoPhongDangSuDung(); 
        cb_phone.addItem("");
        dsidKH.forEach(e -> {
            cb_phone.addItem(e);
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        pnl = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        pnlData = new javax.swing.JPanel();
        cb_phone = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tbl_phongTrong = new rojeru_san.complementos.RSTableMetro();
        jPanel4 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel8 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        tf_phone = new javax.swing.JTextField();
        jPanel14 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        tf_tenKH = new javax.swing.JTextField();
        jPanel9 = new javax.swing.JPanel();
        jPanel10 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        tf_tenPhong = new javax.swing.JTextField();
        jPanel12 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        tf_ngayNhanPhong = new javax.swing.JTextField();
        jPanel13 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        tf_maHD = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setBorder(javax.swing.BorderFactory.createEmptyBorder(10, 10, 10, 10));
        jPanel3.setPreferredSize(new java.awt.Dimension(1600, 964));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setPreferredSize(new java.awt.Dimension(1090, 944));

        pnl.setBackground(new java.awt.Color(255, 255, 255));

        jScrollPane1.setBackground(new java.awt.Color(255, 255, 255));
        jScrollPane1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Danh sách phòng đang sử dụng:", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 24))); // NOI18N
        jScrollPane1.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);

        pnlData.setBackground(new java.awt.Color(255, 255, 255));
        pnlData.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT, 20, 20));
        jScrollPane1.setViewportView(pnlData);

        javax.swing.GroupLayout pnlLayout = new javax.swing.GroupLayout(pnl);
        pnl.setLayout(pnlLayout);
        pnlLayout.setHorizontalGroup(
            pnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 900, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        pnlLayout.setVerticalGroup(
            pnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlLayout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 767, Short.MAX_VALUE)
                .addGap(0, 0, 0))
        );

        cb_phone.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        cb_phone.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cb_phoneActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel3.setText("Lọc theo số điện thoại:");

        jPanel7.setBackground(new java.awt.Color(255, 255, 255));

        jButton1.setBackground(new java.awt.Color(0, 204, 204));
        jButton1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/chuyenPhong_chuyen30.png"))); // NOI18N
        jButton1.setText("Chuyển phòng");
        jButton1.setBorder(javax.swing.BorderFactory.createEmptyBorder(5, 30, 5, 30));
        jButton1.setBorderPainted(false);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel7.add(jButton1);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(447, 447, 447)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(cb_phone, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pnl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, 900, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cb_phone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(53, Short.MAX_VALUE))
        );

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setPreferredSize(new java.awt.Dimension(594, 940));

        jPanel5.setBackground(new java.awt.Color(255, 255, 255));
        jPanel5.setPreferredSize(new java.awt.Dimension(500, 462));

        tbl_phongTrong.setBackground(new java.awt.Color(204, 204, 204));
        tbl_phongTrong.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Mã phòng", "Loại phòng", "Sức chứa", "Giá"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tbl_phongTrong.setColorBackgoundHead(new java.awt.Color(0, 153, 153));
        tbl_phongTrong.setColorBordeFilas(new java.awt.Color(0, 153, 153));
        tbl_phongTrong.setColorBordeHead(new java.awt.Color(0, 102, 102));
        tbl_phongTrong.setColorFilasBackgound2(new java.awt.Color(153, 255, 204));
        tbl_phongTrong.setRowHeight(30);
        tbl_phongTrong.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        tbl_phongTrong.getTableHeader().setReorderingAllowed(false);
        tbl_phongTrong.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbl_phongTrongMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tbl_phongTrong);

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setText("Danh sách phòng trống");
        jPanel4.add(jLabel1);

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 652, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 357, Short.MAX_VALUE))
        );

        jPanel8.setBackground(new java.awt.Color(255, 255, 255));
        jPanel8.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Thông tin khách hàng", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 24))); // NOI18N

        jPanel6.setBackground(new java.awt.Color(255, 255, 255));
        jPanel6.setLayout(new java.awt.BorderLayout());

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel2.setText("Số điện thoại:");
        jPanel6.add(jLabel2, java.awt.BorderLayout.PAGE_START);

        tf_phone.setEditable(false);
        tf_phone.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jPanel6.add(tf_phone, java.awt.BorderLayout.CENTER);

        jPanel14.setBackground(new java.awt.Color(255, 255, 255));
        jPanel14.setLayout(new java.awt.BorderLayout());

        jLabel9.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel9.setText("Tên khách hàng:");
        jPanel14.add(jLabel9, java.awt.BorderLayout.PAGE_START);

        tf_tenKH.setEditable(false);
        tf_tenKH.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jPanel14.add(tf_tenKH, java.awt.BorderLayout.CENTER);

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel14, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel14, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel9.setBackground(new java.awt.Color(255, 255, 255));
        jPanel9.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Thông tin phòng", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 24))); // NOI18N

        jPanel10.setBackground(new java.awt.Color(255, 255, 255));
        jPanel10.setLayout(new java.awt.BorderLayout());

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel4.setText("Tên phòng:");
        jPanel10.add(jLabel4, java.awt.BorderLayout.PAGE_START);

        tf_tenPhong.setEditable(false);
        tf_tenPhong.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jPanel10.add(tf_tenPhong, java.awt.BorderLayout.CENTER);

        jPanel12.setBackground(new java.awt.Color(255, 255, 255));
        jPanel12.setLayout(new java.awt.BorderLayout());

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel6.setText("Ngày nhận phòng:");
        jPanel12.add(jLabel6, java.awt.BorderLayout.PAGE_START);

        tf_ngayNhanPhong.setEditable(false);
        tf_ngayNhanPhong.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jPanel12.add(tf_ngayNhanPhong, java.awt.BorderLayout.CENTER);

        jPanel13.setBackground(new java.awt.Color(255, 255, 255));
        jPanel13.setLayout(new java.awt.BorderLayout());

        jLabel8.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel8.setText("Mã hoá đơn:");
        jPanel13.add(jLabel8, java.awt.BorderLayout.PAGE_START);

        tf_maHD.setEditable(false);
        tf_maHD.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jPanel13.add(tf_maHD, java.awt.BorderLayout.CENTER);

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel13, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel13, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel9, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, 658, Short.MAX_VALUE)))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, 399, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 912, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 664, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 938, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 1614, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tbl_phongTrongMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbl_phongTrongMouseClicked
        // TODO add your handling code here:
        int row = tbl_phongTrong.getSelectedRow(); 
        idSelectedPhongMoi = model.getValueAt(row, 0).toString();
    }//GEN-LAST:event_tbl_phongTrongMouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        if (chuyenPhong()) {
            JOptionPane.showMessageDialog(null, "Chuyển phòng thành công");
//            dsP_fullCol.getPanel_Container_ListPhong().removeAll();
            loadDSPhongDangSuDung();
            idSelectedPhongCu = null;
//            loadDSPhongTrong();
             model.setRowCount(0);
            tf_phone.setText("");
            tf_tenKH.setText("");
            tf_tenPhong.setText("");
            tf_ngayNhanPhong.setText("");
            tf_maHD.setText("");
            
            // reset combobox
            cb_phone.removeAllItems(); // xoá là nó kích hoạt sự kiện của combobox
//            cb_phone.addItem("");
//            ArrayList<String> dsidKH = daoctp.getMaKHtheoPhongDangSuDung(); 
//            dsidKH.forEach(e -> {
//                cb_phone.addItem(e);
//                System.out.println(e);
//            });
//            cb_phone.repaint();
        } else {
//            JOptionPane.showMessageDialog(null, "Chuyển phòng thất bại");
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void cb_phoneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cb_phoneActionPerformed
        // TODO add your handling code here:
        if (cb_phone.getSelectedItem() != null) {
            String id = cb_phone.getSelectedItem().toString();

            if (id.equals("")) {
                ArrayList<String> dsIdPhongDsdTheoMaKH = daoctp.getMaPhongTheoKH(id);
                pnlData.removeAll();

                for (Panel_Phong i : dsPnlPhong) {
                    pnlData.add(i);
                }
                pnlData.revalidate();
                pnlData.repaint();
            } else {
                ArrayList<String> dsIdPhongDsdTheoMaKH = daoctp.getMaPhongTheoKH(id);
                pnlData.removeAll();

                for (Panel_Phong i : dsPnlPhong) {
                    if (dsIdPhongDsdTheoMaKH.contains(i.getId())) {
                        pnlData.add(i);
                    }
                }
                pnlData.revalidate();
                pnlData.repaint();
            }
        }  else { // load lại combobox khi được xoá ở sự kiện chuyển phòng
            cb_phone.addItem("");
            ArrayList<String> dsidKH = daoctp.getMaKHtheoPhongDangSuDung(); 
            dsidKH.forEach(e -> {
                cb_phone.addItem(e);
                System.out.println(e);
            });
        }
        tbl_phongTrong.clearSelection();
        model.setRowCount(0);
        dsPnlPhong.forEach(e -> {
            e.setBorder(null);
        });
    }//GEN-LAST:event_cb_phoneActionPerformed
    public boolean chuyenPhong() {
        if (idSelectedPhongCu == null) {
            JOptionPane.showMessageDialog(null, "Vui lòng chọn phòng đang sử dụng");
            return false;
        } else if (idSelectedPhongMoi == null) {
            JOptionPane.showMessageDialog(null, "Vui lòng chọn phòng trống");
            return false;
        } else {
            // Phòng cũ là phòng đang sử dụng. Phòng mới là phòng sẽ chuyển. Đang sử dụng đồng nghĩa vs mới nhất luôn.
//            ArrayList<ChitTietPhongHoaDon> dsctpTheoMa = daoctp.getDStheoMaPhong(idSelectedPhongCu); // Lấy all chi tiết phòng theo phòng
//            hdPhongDSD_MoiNhat = dsctpTheoMa.getLast().getHoaDon(); // Lấy Hoá đơn mới nhất của chi tiết phòng theo mã phòng. Hoá đơn mới nhất là hoá đơn chứa các phòng đang dc sử dụng.
            LocalDateTime now = LocalDateTime.now(); // Thòi gian trả phòng | nhận phòng

            // Ghi chú chi tiết phòng cũ: mã phòng trước đó mã phòng mới. VD: MP001 MP002. cắt lấy MP001
            // Giả sử có chi tiết phòng của MP001. MP001 sang MP003.
            // Ghi chú theo quy luật: nếu là phòng vừa đặt thì ghi chú là MP000 Đang sử dụng.
            // Nếu chuyển sang phòng mới thì cập nhật lại ghi chú của node phía trước là MP000 MP003 
            // Chi tiết phòng mới: ghi chú là MP003 Đang sử dụng
            
            // Chặn vòng lặp khi chuyển từ phòng cũ sang mới rồi lại về cũ
            for (String i : daoctp.getDsIdTheoMaHoaDon(hdPhongDSD_MoiNhat.getMaHoaDon())) {
                if (idSelectedPhongMoi.equals(i.trim())) {
                    JOptionPane.showMessageDialog(null, "Không được chuyển lại phòng cũ");
                    return false;
                }
                    
            }
            // Lấy chi tiết phòng cũ
            ChitTietPhongHoaDon ctPhongCu = dsctpTheoMa.get(dsctpTheoMa.size() - 1); 
            String ghiChuPhongCu = ctPhongCu.getGhiChu().substring(0, 5) + " " + idSelectedPhongMoi;
            // Update giờ ra cho phòng cũ (ghi chú chi tiết phòng) 
            if (!daoctp.updateGioRa(idSelectedPhongCu, hdPhongDSD_MoiNhat.getMaHoaDon(), now, ghiChuPhongCu)) {
                return false;
            }
            // updqte trạng thái phòng cũ
            if (!daop.capNhatTrangThaiPhong(idSelectedPhongCu, 0)) {
                return false;
            }
            // tạo chi tiết phòng mới (ghi chú chi tiết phòng)
            Phong phongMoi = I_CRUD.findById(idSelectedPhongMoi, new Phong());
            // Ghi chú cho phòng mới
            String ghiChuPhongMoi = idSelectedPhongCu + " Đang sử dụng";
            ChitTietPhongHoaDon ctp_new = new ChitTietPhongHoaDon(now, null, ghiChuPhongMoi, hdPhongDSD_MoiNhat, phongMoi);
            if (!daoctp.themCTHD_PMoi(ctp_new)) {
                return false;
            }
            // update trạng thái phòng mới
            if (!daop.capNhatTrangThaiPhong(idSelectedPhongMoi, 2)) {
                return false;
            }
        }
        return true;
    }
    public void loadDSPhongDangSuDung(){
        // Xóa danh sách phòng trống cũ
        pnlData.removeAll();
//        repaint();
        
        // Lấy danh sách phòng trống từ CSDL
        ArrayList<entity.Phong> dspdsd = daop.getPhongTheoTrangThai(2); // 1 là ds phòng đang sử dụng
        
        int tongPhong = dspdsd.size();
        int soDong;
        if (tongPhong % 3 == 0) {
            soDong = tongPhong / 3;
        } else {
            soDong = tongPhong / 3 + 1; // cộng 1 vì số dư <= 2 và 1 dòng thì chứa dc 3 phòng
        }
        pnlData.setPreferredSize(new Dimension(890, soDong * 135 + (soDong + 1) * 20 )); // 20 là gap, 135 là chiều cao 1 phòng
        dsPnlPhong.clear();
        for (int i = 0; i < dspdsd.size(); i++) {
            Panel_Phong p = new Panel_Phong(dspdsd.get(i));
            pnlData.add(p);
//            if (p.getMouseListeners().length > 0) 
//                System.out.println("Đã xoá dc");
//            else
//                System.out.println("chưa dc");
            p.addMouseListener(new java.awt.event.MouseAdapter() {
                @Override
                public void mouseClicked(java.awt.event.MouseEvent evt) {
                    
                    Border border = new LineBorder(Color.ORANGE, 4, true);
//                    for (Panel_Phong i : dspnlp) {
//                        if (i.equals(p))
//                            i.setBorder(border);
//                        else
//                            i.setBorder(null);
//                    }
                    if (previousSelectedRoom != null) {
                        previousSelectedRoom.setBorder(null); // Cập nhật viền cho phần tử trước đó
                    }
                    p.setBorder(border); // Cập nhật viền cho phần tử mới
                    previousSelectedRoom = p;
                    idSelectedPhongCu = p.getId();
                    dsctpTheoMa = daoctp.getDStheoMaPhong(idSelectedPhongCu);
                    hdPhongDSD_MoiNhat = dsctpTheoMa.getLast().getHoaDon();
                    if (hdPhongDSD_MoiNhat != null)
                        hdPhongDSD_MoiNhat = dsctpTheoMa.getLast().getHoaDon();
                    loadDSPhongTrong();
                    // show detail 
                    KhachHang tmpKH = hdPhongDSD_MoiNhat.getKhachHang();
                    tf_phone.setText(tmpKH.getSoDienThoai());
                    tf_tenKH.setText(tmpKH.getTenKhachHang());
                    tf_tenPhong.setText(p.getTenPhong());
                    tf_ngayNhanPhong.setText(dsctpTheoMa.getLast().getThoiGianNhanPhong().format(DateTimeFormatter.ofPattern("yyyy-MM-dd HH:mm:ss")));
                    tf_maHD.setText(hdPhongDSD_MoiNhat.getMaHoaDon());
                }
            });
            dsPnlPhong.add(p);
            pnlData.revalidate();
            pnlData.repaint();
        }
    }
    public void loadDSPhongTrong() {
        model.setRowCount(0);
        idSelectedPhongMoi = null;
        int row = tbl_phongTrong.getSelectedRow();
        ArrayList<Phong> dspt = daop.getPhongTheoTrangThai(0);
        if (hdPhongDSD_MoiNhat != null) {
            ArrayList<String> dsid_phong = daoctp.getDsIdTheoMaHoaDon(hdPhongDSD_MoiNhat.getMaHoaDon());
            for (Phong i : dspt) {
                if (!dsid_phong.contains(i.getMaPhong())) {
                    String maphong = i.getMaPhong();
                    String loaiphong = (i.getLoaiPhong()).getLoaiPhong();
//                    System.out.println(i.getLoaiPhong());
                    String succhua = String.valueOf(i.getSucChuaToiDa());
                    String gia = String.valueOf(i.getGia());
                    Object[] rowData = {maphong, loaiphong, succhua, gia};
                    model.addRow(rowData);
                }
            }
        } else {
            for (Phong i : dspt) {
                String maphong = i.getMaPhong();
                String loaiphong = (i.getLoaiPhong()).getLoaiPhong();
//                System.out.println(i.getLoaiPhong());
                String succhua = String.valueOf(i.getSucChuaToiDa());
                String gia = String.valueOf(i.getGia());
                Object[] rowData = {maphong, loaiphong, succhua, gia};
                model.addRow(rowData);
            }
        }
        
    } 
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(GD_XuLy_ChuyenPhong.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(GD_XuLy_ChuyenPhong.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(GD_XuLy_ChuyenPhong.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(GD_XuLy_ChuyenPhong.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GD_XuLy_ChuyenPhong().setVisible(true);
            }
        });
    }
private DAO_Phong daop = new DAO_Phong();
private DAO_ChiTietPhong_HoaDon daoctp = new DAO_ChiTietPhong_HoaDon();
ArrayList<entity.Phong> dspdsd = new ArrayList<>();
private String  idSelectedPhongCu = null;
private String idSelectedPhongMoi = null;
private Panel_Phong previousSelectedRoom = null;
private DefaultTableModel model;
private ArrayList<ChitTietPhongHoaDon> dsctpTheoMa = new ArrayList<>();
private HoaDon hdPhongDSD_MoiNhat;
private ArrayList<Panel_Phong> dsPnlPhong = new ArrayList<>();
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> cb_phone;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel14;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JPanel pnl;
    private javax.swing.JPanel pnlData;
    private rojeru_san.complementos.RSTableMetro tbl_phongTrong;
    private javax.swing.JTextField tf_maHD;
    private javax.swing.JTextField tf_ngayNhanPhong;
    private javax.swing.JTextField tf_phone;
    private javax.swing.JTextField tf_tenKH;
    private javax.swing.JTextField tf_tenPhong;
    // End of variables declaration//GEN-END:variables
}
