/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package gui;

import java.util.ArrayList;
import javax.swing.JPanel;
import smallPanel.DanhSachPhong;
import smallPanel.Phong;
import smallPanel.allPhong_LocPhong;

/**
 *
 * @author LENOVO
 */
public class GD_XuLyDanhSachPhong extends javax.swing.JFrame {

    /**
     * Creates new form GD_XuLyDanhSachPhong
     */
    public GD_XuLyDanhSachPhong() {
        initComponents();
                jPanel1.add(createList());
    }

    public ArrayList<Phong> list = new ArrayList<>();
    
        public ArrayList<Phong> tmpData(){
        list.add(new Phong());
        list.add(new Phong());
        list.add(new Phong());
        list.add(new Phong());
        list.add(new Phong());
        list.add(new Phong());
        list.add(new Phong());
        list.add(new Phong());
        list.add(new Phong());
        list.add(new Phong());
        list.add(new Phong());
        list.add(new Phong());
        list.add(new Phong());
        list.add(new Phong());
        list.add(new Phong());
//        list.add(new Phong());
//        list.add(new Phong());
//        list.add(new Phong());
//        list.add(new Phong());
//        list.add(new Phong());
//        list.add(new Phong());
//        list.add(new Phong());
//        list.add(new Phong());
//        list.add(new Phong());
//        list.add(new Phong());
//        list.add(new Phong());
//        list.add(new Phong());
//        list.add(new Phong());
//        list.add(new Phong());
//        list.add(new Phong());
//        list.add(new Phong());
//        list.add(new Phong());
//        list.add(new Phong());
//        list.add(new Phong());
//        list.add(new Phong());
//        list.add(new Phong());
//        list.add(new Phong());
//        list.add(new Phong());
//        list.add(new Phong());
//        list.add(new Phong());
//        list.add(new Phong());
//        list.add(new Phong());
//        list.add(new Phong());
//        list.add(new Phong());
//        list.add(new Phong());
//        list.add(new Phong());
//        list.add(new Phong());
//        list.add(new Phong());
//        list.add(new Phong());
//        list.add(new Phong());
//        list.add(new Phong());
//        list.add(new Phong());
//        list.add(new Phong());
//        list.add(new Phong());
        return list;
    }
    public JPanel createList(){
        ArrayList<Phong> dataPhong = tmpData();
        allPhong_LocPhong allPhong_LocPhong = new allPhong_LocPhong(dataPhong);
        String[] title = {"Lọc theo loại phòng","Lọc theo sức chứa","lọc theo ngày"};
        String[] option1 = {"Không","Phòng thường","Phòng VIP"};
        String[] option2 = {"Không","5","10","20"};
        String[] option3 = {"Không","Trống","Đang Đợi","Bận"};
        allPhong_LocPhong.setAllOptionLabel(title);
        allPhong_LocPhong.setCombo1(option1);
        allPhong_LocPhong.setCombo2(option2);
        allPhong_LocPhong.setCombo3(option3);
        tmpDSPhong = allPhong_LocPhong.getDsPhong();
        tmpAllPhong_LocPhong = allPhong_LocPhong;
        return allPhong_LocPhong;
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(1620, 964));
        setMinimumSize(new java.awt.Dimension(1620, 964));
        setPreferredSize(new java.awt.Dimension(1620, 964));

        jPanel1.setBackground(new java.awt.Color(204, 204, 255));
        jPanel1.setMaximumSize(new java.awt.Dimension(1080, 698));
        jPanel1.setMinimumSize(new java.awt.Dimension(1080, 698));
        jPanel1.setPreferredSize(new java.awt.Dimension(1080, 698));
        jPanel1.setVerifyInputWhenFocusTarget(false);
        jPanel1.setLayout(new java.awt.GridLayout());

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 1614, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 964, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GD_XuLyDanhSachPhong.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GD_XuLyDanhSachPhong.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GD_XuLyDanhSachPhong.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GD_XuLyDanhSachPhong.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GD_XuLyDanhSachPhong().setVisible(true);
            }
        });
    }
    public DanhSachPhong tmpDSPhong;
     public allPhong_LocPhong tmpAllPhong_LocPhong;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
