/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package gui;

import com.formdev.flatlaf.themes.FlatMacLightLaf;
import java.awt.Color;
import java.awt.LayoutManager;
import java.util.ArrayList;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.UIManager;
import smallPanel.DanhSachPhong;
import smallPanel.Phong;
import smallPanel.allPhong_LocPhong;

/**
 *
 * @author Minh Hieu
 */
public class tesstPhong extends javax.swing.JFrame {

    /**
     * Creates new form tesstPhong
     */
    public tesstPhong() {
        initComponents();
        jPanel1.add(createList());
        
//        testClick.setName("ButtonClick");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    
    public ArrayList<Phong> tmpData(){
        list.add(new Phong());
        list.add(new Phong());
        list.add(new Phong());
        list.add(new Phong());
        list.add(new Phong());
        list.add(new Phong());
        list.add(new Phong());
        list.add(new Phong());
        list.add(new Phong());
        list.add(new Phong());
        list.add(new Phong());
        list.add(new Phong());
        list.add(new Phong());
//        list.add(new Phong());
//        list.add(new Phong());

        return list;
    }
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jInternalFrame1 = new javax.swing.JInternalFrame();
        jPanel1 = new javax.swing.JPanel();

        jInternalFrame1.setVisible(true);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        setMaximumSize(new java.awt.Dimension(1080, 698));
        setMinimumSize(new java.awt.Dimension(1080, 698));
        setPreferredSize(new java.awt.Dimension(1080, 698));

        jPanel1.setBackground(new java.awt.Color(204, 204, 255));
        jPanel1.setMaximumSize(new java.awt.Dimension(1080, 698));
        jPanel1.setMinimumSize(new java.awt.Dimension(1080, 698));
        jPanel1.setPreferredSize(new java.awt.Dimension(1080, 698));
        jPanel1.setVerifyInputWhenFocusTarget(false);
        jPanel1.setLayout(new java.awt.GridLayout(1, 0));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 1074, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 702, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    public JPanel createList(){
        ArrayList<Phong> dataPhong = tmpData();
        allPhong_LocPhong allPhong_LocPhong = new allPhong_LocPhong(dataPhong);
        String[] title = {"Lọc theo loại phòng","Lọc theo sức chứa","lọc theo ngày"};
        String[] option1 = {"Không","Phòng thường","Phòng VIP"};
        String[] option2 = {"Không","5","10","20"};
        String[] option3 = {"Không","Trống","Đang Đợi","Bận"};
        allPhong_LocPhong.setAllOptionLabel(title);
        allPhong_LocPhong.setCombo1(option1);
        allPhong_LocPhong.setCombo2(option2);
        allPhong_LocPhong.setCombo3(option3);
        tmpDSPhong = allPhong_LocPhong.getDsPhong();
        tmpAllPhong_LocPhong = allPhong_LocPhong;
        return allPhong_LocPhong;
    }
    
   
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        FlatMacLightLaf.setup();
        UIManager.put( "Button.arc", 10 );
        UIManager.put( "Component.arc", 10 );
        UIManager.put( "ProgressBar.arc", 10 );
        UIManager.put( "TextComponent.arc", 10 );

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new tesstPhong().setVisible(true);
            }
        });
    }
    
    public ArrayList<Phong> list = new ArrayList<>();
    public DanhSachPhong tmpDSPhong;
     public allPhong_LocPhong tmpAllPhong_LocPhong;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JInternalFrame jInternalFrame1;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
