/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package smallPanel;

import java.text.SimpleDateFormat;
import java.util.Date;

/**
 *
 * @author Admin
 */
public class navBar extends javax.swing.JPanel implements Runnable{

    /**
     * Creates new form navBar
     */
    public navBar() {
        
        //Tạo Luồng Để run()
        thread = new Thread(this);
        thread.start();
        
        initComponents();
    }
    public  void run(){
        try {
			Date thoiGianHienTai = new Date();
			SimpleDateFormat sdf_Gio = new SimpleDateFormat("HH:mm:ss");
			SimpleDateFormat sdf_Ngay = new SimpleDateFormat("dd/MM/yyyy");
			while (true) {
				thoiGianHienTai = new Date(); // lấy thời gian hiện tại
				String ngayTrongTuan = "";
				if (thoiGianHienTai.getDay() == 0)
					ngayTrongTuan = "Chủ nhật, ";
				else
					ngayTrongTuan = "Thứ " + (thoiGianHienTai.getDay() + 1) + ", ";// do getDay() tính từ 1.
				thread.sleep(1000); // cho phép ngủ trong khoảng 1000 mns =1s
				// lấy thời gian hiện tại vào giờ vào
                                System.out.println("mainFrame.mainFrame.run()");
                                name_Account1.setText(
                                        sdf_Gio.format(thoiGianHienTai) + " " + ngayTrongTuan +
                                        sdf_Ngay.format(thoiGianHienTai)
                                        );
                                
			}
		} catch (InterruptedException e) {
			e.printStackTrace();
		}
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        leftPanel = new javax.swing.JPanel();
        name_Account = new javax.swing.JLabel();
        icon_Account = new javax.swing.JLabel();
        name_Account1 = new javax.swing.JLabel();
        rightPanel = new javax.swing.JPanel();
        homaPage = new javax.swing.JPanel();
        homePageTextIcon = new javax.swing.JLabel();
        room = new javax.swing.JPanel();
        roomTextIcon = new javax.swing.JLabel();

        setBackground(new java.awt.Color(0, 153, 255));
        setPreferredSize(new java.awt.Dimension(1536, 66));
        setLayout(null);

        leftPanel.setBackground(new java.awt.Color(0, 153, 255));
        leftPanel.setLayout(new java.awt.GridBagLayout());

        name_Account.setBackground(new java.awt.Color(255, 255, 255));
        name_Account.setFont(new java.awt.Font("Segoe UI Black", 1, 24)); // NOI18N
        name_Account.setForeground(new java.awt.Color(255, 255, 255));
        name_Account.setText("Trần Thị Thúy Vy");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(3, 72, 0, 63);
        leftPanel.add(name_Account, gridBagConstraints);

        icon_Account.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8-account-60.png"))); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(0, 9, 0, 0);
        leftPanel.add(icon_Account, gridBagConstraints);

        name_Account1.setBackground(new java.awt.Color(255, 255, 255));
        name_Account1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        name_Account1.setForeground(new java.awt.Color(255, 255, 255));
        name_Account1.setText("11:30:45PM 20-10-2023");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(32, 73, 0, 64);
        leftPanel.add(name_Account1, gridBagConstraints);

        add(leftPanel);
        leftPanel.setBounds(0, 0, 360, 70);

        rightPanel.setBackground(new java.awt.Color(0, 153, 255));
        rightPanel.setLayout(new java.awt.GridBagLayout());

        homaPage.setBackground(new java.awt.Color(0, 153, 255));

        homePageTextIcon.setFont(new java.awt.Font("Segoe UI Black", 0, 18)); // NOI18N
        homePageTextIcon.setForeground(new java.awt.Color(255, 255, 255));
        homePageTextIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8-home-40.png"))); // NOI18N
        homePageTextIcon.setText("Trang Chủ");

        javax.swing.GroupLayout homaPageLayout = new javax.swing.GroupLayout(homaPage);
        homaPage.setLayout(homaPageLayout);
        homaPageLayout.setHorizontalGroup(
            homaPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
            .addGroup(homaPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(homaPageLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(homePageTextIcon)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        homaPageLayout.setVerticalGroup(
            homaPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
            .addGroup(homaPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(homaPageLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(homePageTextIcon)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        rightPanel.add(homaPage, new java.awt.GridBagConstraints());

        room.setBackground(new java.awt.Color(0, 153, 255));

        roomTextIcon.setFont(new java.awt.Font("Segoe UI Black", 0, 18)); // NOI18N
        roomTextIcon.setForeground(new java.awt.Color(255, 255, 255));
        roomTextIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8-micro-40.png"))); // NOI18N
        roomTextIcon.setText("Xử lý");

        javax.swing.GroupLayout roomLayout = new javax.swing.GroupLayout(room);
        room.setLayout(roomLayout);
        roomLayout.setHorizontalGroup(
            roomLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 134, Short.MAX_VALUE)
            .addGroup(roomLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(roomLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(roomTextIcon)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        roomLayout.setVerticalGroup(
            roomLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 40, Short.MAX_VALUE)
            .addGroup(roomLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(roomLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(roomTextIcon)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.insets = new java.awt.Insets(0, 15, 0, 0);
        rightPanel.add(room, gridBagConstraints);

        add(rightPanel);
        rightPanel.setBounds(360, 0, 1180, 70);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel homaPage;
    private javax.swing.JLabel homePageTextIcon;
    private javax.swing.JLabel icon_Account;
    private javax.swing.JPanel leftPanel;
    private javax.swing.JLabel name_Account;
    public javax.swing.JLabel name_Account1;
    private javax.swing.JPanel rightPanel;
    private javax.swing.JPanel room;
    private javax.swing.JLabel roomTextIcon;
    // End of variables declaration//GEN-END:variables
    private Thread thread = null;
}
